<?php
if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');
/*********************************************************************************
 * SugarCRM is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004 - 2010 SugarCRM Inc.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo. If the display of the logo is not reasonably feasible for
 * technical reasons, the Appropriate Legal Notices must display the words
 * "Powered by SugarCRM".
 ********************************************************************************/

  /*********************************************************************************
  *
  * File generated by the RAPIRA Translation Suite ----------
  *
  ***********************************************************************likhobory*/

  /*********************************************************************************
  * Description : Defines the Russian language pack for the base application.
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s):
  *********************************************************************************/

$mod_strings = array (

    'LBL_GOOD_FILE' => 'Файл импорта успешно прочитан',
    'LBL_RECORDS_SKIPPED_DUE_TO_ERROR' => 'Записи пропущены из-за возникшей ошибки',
    'LBL_UPDATE_SUCCESSFULLY' => 'записей успешно обновлены',
    'LBL_SUCCESSFULLY_IMPORTED' => 'записей успешно созданы',
    'LBL_STEP_4_TITLE' => 'Шаг 4: Импорт файла',
    'LBL_STEP_5_TITLE' => 'Шаг 5: Просмотр результатов',
    'LBL_CUSTOM_ENCLOSURE' => 'Поля ограничены символом:',
    'LBL_ERROR_UNABLE_TO_PUBLISH' => 'Нельзя опубликовать схему. Уже существует другая схема импорта с аналогичным названием.',
    'LBL_ERROR_UNABLE_TO_UNPUBLISH' => 'Нельзя отменить публикацию схемы импорта, принадлежащую другому пользователю. Необходимо чтобы схема импорта с аналогичным названием принадлежала вам.',
    'LBL_ERROR_IMPORTS_NOT_SET_UP' => 'Импорт не настроен для данного типа модуля',
    'LBL_IMPORT_TYPE' => 'Параметры импорта',
    'LBL_IMPORT_BUTTON' => 'Создание записей',
    'LBL_UPDATE_BUTTON' => 'Создание и обновление записей',
    'LBL_ERROR_INVALID_BOOL'=>'Неверное логическое значение',
    'LBL_NO_ID' => 'Требуется ID',
    'LBL_PRE_CHECK_SKIPPED' => 'Предварительная проверка пропущена',
    'LBL_IMPORT_ERROR' => 'Ошибка импорта',
    'LBL_ERROR' => 'Error',
    'LBL_NOLOCALE_NEEDED' => 'Перекодировка не требуется',
    'LBL_FIELD_NAME' => 'Название поля',
    'LBL_VALUE' => 'Значение',
    'LBL_ROW_NUMBER' => 'Номер строки',
    'LBL_NONE' => 'Нет',
    'LBL_REQUIRED_VALUE' => 'Требуемое значение отсутствует',
    'LBL_ID_EXISTS_ALREADY' => 'Данный ID уже присутствует в этой таблице',
    'LBL_ASSIGNED_USER' => 'Если пользователь не существует - используйте текущего пользователя',
    'LBL_SHOW_HIDDEN' => 'Показать поля, которые не могут быть корректно импортированы',                           ///
    'LBL_UPDATE_RECORDS' => 'Обновление существующих записей (операцию нельзя отменить)',
    'LBL_TEST'=> 'Тестирование импорта (данные НЕ добавляются и НЕ изменяются)',
    'LBL_TRUNCATE_TABLE' => 'Очистить таблицу перед импортом (удаление всех записей)',
    'LBL_RELATED_ACCOUNTS' => 'Do not create related accounts',                    ///
    'LBL_NO_DATECHECK' => 'Пропустить проверку даты (это ускорит выполнение операции, но приведет к ошибке, если будет обнаружена хотя бы одна неверная дата)',

    'LBL_NO_EMAILS' => 'Не отсылать предупреждения Email при осуществлении импорта',
    'LBL_NO_PRECHECK' => 'Native Format mode',   ///
    'LBL_STRICT_CHECKS' => 'Use strict ruleset (Check Email addresses and phone numbers too)',  ///
    'LBL_ERROR_SELECTING_RECORD' => 'Ошибка выбора записи:',
    'LBL_ERROR_DELETING_RECORD' => 'Ошибка удаления записи:',
    'LBL_NOT_SET_UP' => 'Нельзя выполнить импорт в данном типе модуля',
    'LBL_ARE_YOU_SURE' => 'Вы уверены? В результате будут удалены все данные из этого модуля.',
    'LBL_NO_RECORD' => 'Нет записи для обновления с данным ID',
    'LBL_NOT_SET_UP_FOR_IMPORTS' => 'Нельзя выполнить импорт в данном типе модуля',
    'LBL_DEBUG_MODE' => 'Включение режима отладки',
    'LBL_ERROR_INVALID_ID' => 'Указано слишком длинное значение ID. В поле может быть введено не более 36 символов.',
    'LBL_ERROR_INVALID_PHONE' => 'Неверный телефонный номер',
    'LBL_ERROR_INVALID_NAME' => 'Слишком длинное значение',
    'LBL_ERROR_INVALID_VARCHAR' => 'Слишком длинное значение',
    'LBL_ERROR_INVALID_DATE' => 'Неверное значение даты',
    'LBL_ERROR_INVALID_DATETIME' => 'Неверное значение даты/времени',
	'LBL_ERROR_INVALID_DATETIMECOMBO' => 'Неверное значение даты/времени',
    'LBL_ERROR_INVALID_TIME' => 'Неверное значение времени',
    'LBL_ERROR_INVALID_INT' => 'Неверное целое значение',
    'LBL_ERROR_INVALID_NUM' => 'Неверный номер',
    'LBL_ERROR_INVALID_TIME' => 'Неверное значение времени',
    'LBL_ERROR_INVALID_EMAIL'=>'Неверный E-mail',
    'LBL_ERROR_INVALID_BOOL'=>'Неверное значение (должно быть 1 или 0)',
    'LBL_ERROR_INVALID_DATE'=>'Неверное значение даты',
    'LBL_ERROR_INVALID_USER'=>'Неверное имя пользователя или ID',
    'LBL_ERROR_INVALID_TEAM' => 'Invalid team name or ID',
    'LBL_ERROR_INVALID_ACCOUNT' => 'Неверная учетная запись или ID',
    'LBL_ERROR_INVALID_RELATE' => 'Неверное отношение',
    'LBL_ERROR_INVALID_CURRENCY' => 'Неверное значение валюты',
    'LBL_ERROR_INVALID_FLOAT' => 'Неверное число с плавающей запятой',
    'LBL_ERROR_NOT_IN_ENUM' => 'Значение отсутствует в списке. Допустимые значения: ',
    'LBL_NOT_MULTIENUM' => 'Not a MultiEnum',                                                   ///
    'LBL_IMPORT_MODULE_NO_TYPE' => 'Нельзя выполнить импорт в данном типе модуля',
    'LBL_IMPORT_MODULE_NO_USERS' => 'ПРЕДУПРЕЖДЕНИЕ: В системе не зарегистрировано ни одного пользователя. Если импорт будет произведен до того, как в систему будет добавлен пользователь - все записи будут присвоены администратору.',
    'LBL_IMPORT_MODULE_MAP_ERROR' => 'Нельзя опубликовать схему. Уже существует другая схема импорта с аналогичным названием.',
    'LBL_IMPORT_MODULE_MAP_ERROR2' => 'Нельзя отменить публикацию схемы импорта, принадлежащую другому пользователю. Необходимо чтобы схема импорта с аналогичным названием принадлежала вам.',


'LBL_IMPORT_MODULE_NO_DIRECTORY' => 'Директория ' ,
'LBL_IMPORT_MODULE_NO_DIRECTORY_END' => ' отсутствует или недоступна для записи' ,
'LBL_IMPORT_MODULE_ERROR_NO_UPLOAD' => 'Файл загружен неудачно. Возможно, значение \'upload_max_filesize\' в Вашем файле php.ini слишком мало' ,
'LBL_IMPORT_MODULE_ERROR_LARGE_FILE' => 'Файл слишком большой. Допустимый максимум:' ,
'LBL_IMPORT_MODULE_ERROR_LARGE_FILE_END' => 'байт. Измените параметр $sugar_config[\'upload_maxsize\'] в файле config.php' ,
'LBL_MODULE_NAME' => 'Импорт' ,
'LBL_TRY_AGAIN' => 'Попробовать ещё раз' ,
'LBL_ERROR' => 'Ошибка:' ,
'ERR_IMPORT_SYSTEM_ADMININSTRATOR'  => 'Вы не можете импортировать пользователя, имеющего права системного администратора',
'ERR_MULTIPLE' => 'Несколько колонок имеют одни и те же имена.' ,
'ERR_MISSING_REQUIRED_FIELDS' => 'Пропущены обязательные поля:' ,
'ERR_MISSING_MAP_NAME' => 'Отсутствует название схемы импорта',
'ERR_SELECT_FULL_NAME' => 'Вы не можете выбрать Полное имя, когда Имя и Фамилия уже выбраны.' ,
'ERR_SELECT_FILE' => 'Выбор файла для загрузки.' ,
'LBL_SELECT_FILE' => 'Выбор файла:' ,
'LBL_CUSTOM' => 'Пользовательский' ,
'LBL_CUSTOM_CSV' => 'CVS-файл' ,
'LBL_CSV' => 'Текстовый файл с запятой в качестве разделителя',
'LBL_TAB' => 'Текстовый файл с символом табуляции в качестве разделителя',
'LBL_CUSTOM_DELIMITED' => 'Текстовый файл с указанным символом в качестве разделителя',
'LBL_CUSTOM_DELIMITER' => 'Поля разделены при помощи:',
'LBL_FILE_OPTIONS' => 'Параметры файла',
'LBL_CUSTOM_TAB' => 'Табулированный текстовый файл' ,
'LBL_DONT_MAP' => '-- Не импортировать это поле --' ,
'LBL_STEP_1_TITLE' => 'Шаг 1: Выбор источника данных и параметров импорта' ,
'LBL_WHAT_IS' => 'Укажите тип источника данных:' ,
'LBL_MICROSOFT_OUTLOOK' => 'Microsoft Outlook' ,
'LBL_ACT' => 'Act!' ,
'LBL_ACT_2005' => 'Act! 2005' ,
'LBL_SALESFORCE' => 'Salesforce.com' ,
'LBL_MY_SAVED' => 'Мои схемы импорта:',
'LBL_PUBLISH' => 'Опубликовать схему' ,
'LBL_DELETE' => 'Удалить схему' ,
'LBL_PUBLISHED_SOURCES' => 'Опубликованные схемы импорта:',
'LBL_UNPUBLISH' => 'Отменить публикацию' ,
'LBL_NEXT' => 'Дальше >' ,
'LBL_BACK' => '< Назад' ,
'LBL_STEP_2_TITLE' => 'Шаг 2: Загрузка файла импорта' ,
'LBL_HAS_HEADER' => 'Имеет заголовки:' ,
'LBL_NUM_1' => '1.' ,
'LBL_NUM_2' => '2.' ,
'LBL_NUM_3' => '3.' ,
'LBL_NUM_4' => '4.' ,
'LBL_NUM_5' => '5.' ,
'LBL_NUM_6' => '6.' ,
'LBL_NUM_7' => '7.' ,
'LBL_NUM_8' => '8.' ,
'LBL_NUM_9' => '9.' ,
'LBL_NUM_10' => '10.' ,
'LBL_NUM_11' => '11.' ,
'LBL_NUM_12' => '12.' ,
'LBL_NOTES' => 'Примечание:',
'LBL_NOW_CHOOSE' => 'Выберите файл для импорта:' ,
'LBL_IMPORT_OUTLOOK_TITLE' => 'Microsoft Outlook 98 - Outlook 2007 могут экспортировать данные в <b>CVS</b> формат, который может использоваться для импорта данных в эту систему.<br> Для экспорта Ваших данных из Outlook, следуйте шагам, приведенным ниже:' ,
'LBL_OUTLOOK_NUM_1' => 'Запустите <b>Outlook</b>' ,
'LBL_OUTLOOK_NUM_2' => 'Выберите меню <b>Файл</b>, затем пункт меню <b>Импорт и Экспорт...</b>' ,
'LBL_OUTLOOK_NUM_3' => 'Выберите <b>Экспорт в файл</b> и нажмите на кнопку <b>Далее</b>' ,
'LBL_OUTLOOK_NUM_4' => 'Выберите <b>Значения, разделенные запятыми (Windows)</b> и нажмите кнопку <b>Далее</b>.<br>  Замечание: Вы можете получить сообщение о необходимости установки компоненты экспортирования' ,
'LBL_OUTLOOK_NUM_5' => 'Выберите папку <b>Контакты</b> и нажмите кнопку <b>Дальше</b>. Вы можете выбрать различные папки контактов, если Ваши контакты размещены в нескольких папках' ,
'LBL_OUTLOOK_NUM_6' => 'Выберите имя файла и нажмите кнопку <b>Далее</b>' ,
'LBL_OUTLOOK_NUM_7' => 'Нажмите кнопку <b>Готово</b>' ,


'LBL_IMPORT_SF_TITLE' => 'Система Salesforce.com может экспортировать данные в формате <b>CSV</b>, который можно использовать для импорта данных в систему. Для экспорта Ваших данных из Salesforce.com, следуйте шагам, приведенным ниже:' ,
'LBL_SF_NUM_1' => 'Откройте Ваш браузер, перейдите на http://www.salesforce.com, и авторизуйтесь, указав Ваш E-mail и пароль' ,
'LBL_SF_NUM_2' => 'Нажмите на закладку <b>Отчеты</b> в верхнем меню' ,
'LBL_SF_NUM_3' => '<b>Для экспортирования Контрагентов:</b> Нажмите на ссылке <b>Активные контрагенты</b> <br><b>Для экспортирования Контактов:</b> Нажмите на ссылке <b>Список рассылок</b>' ,
'LBL_SF_NUM_4' => 'На <b>Шаге 1: Выберите Ваш тип отчёта</b>, затем выберите <b>Табулированный отчёт</b> и нажмите кнопку <b>Дальше</b>' ,
'LBL_SF_NUM_5' => 'На <b>Шаге 2: Выберите колонки отчёта</b>, затем выберите колонки, которые Вы хотите экспортировать и нажмите кнопку <b>Дальше</b>' ,
'LBL_SF_NUM_6' => 'На <b>Шаге 3: Выберите информацию для суммирования</b> и нажмите кнопку <b>Дальше</b>' ,
'LBL_SF_NUM_7' => 'На <b>Шаге 4: Упорядочите колонки отчёта</b> и нажмите кнопку <b>Дальше</b>' ,
'LBL_SF_NUM_8' => 'На <b>Шаге 5: Выберите Ваш критерий отчёта</b>; в качестве <b>Даты начала</b> укажите по возможности наименьшее значение, чтобы заведомо включить всех Ваших Контрагентов. Вы можете также экспортировать подмножество Ваших Контрагентов, используя более точные критерии. По завершении нажмите кнопку <b>Запустить отчёт</b>' ,
'LBL_SF_NUM_9' => 'Отчет будет сгенерирован, и страница покажет <b>Статус генерации отчёта: завершен.</b> Теперь нажмите кнопку <b>Экспорт в Excel</b>' ,
'LBL_SF_NUM_10' => 'Выберите <b>Экспортировать отчёт:</b>, в качестве <b>Формата файла экспорта:</b> укажите <b>Разделенные запятой .csv</b>. Нажмите кнопку <b>Экспорт</b>.' ,
'LBL_SF_NUM_11' => 'Всплывающий диалог позволит Вам сохранить экспортируемый файл на Ваш компьютер.' ,

    'LBL_IMPORT_ACT_TITLE' => 'Act! может экспортировать данные в формат <b>CSV</b> (значения, разделенные запятой), который может быть использован для импорта данных в систему. Для экспорта данных из Act! выполните следующее:',
    'LBL_ACT_NUM_1' => 'Запустите <b>ACT!</b>',
    'LBL_ACT_NUM_2' => 'В меню <b>File</b> выберите <b>Data Exchange</b>, затем <b>Export...</b>',
    'LBL_ACT_NUM_3' => 'В качестве типа файла экспорта выберите <b>Text-Delimited</b>',
    'LBL_ACT_NUM_4' => 'Укажите имя и место сохранения файла с экспортируемыми данными и нажмите кнопку <b>Далее</b>',
    'LBL_ACT_NUM_5' => 'Выберите <b>Contacts records only</b>',
    'LBL_ACT_NUM_6' => 'Нажмите кнопку <b>Options...</b>',
    'LBL_ACT_NUM_7' => 'Выберите <b>Comma</b> в качестве разделителя полей',
    'LBL_ACT_NUM_8' => 'Отметьте параметр <b>Yes, export field names</b> и нажмите кнопку <b>OK</b>',
    'LBL_ACT_NUM_9' => 'Нажмите кнопку <b>Далее</b>',
    'LBL_ACT_NUM_10' => 'Выберите <b>All Records</b> и нажмите кнопку <b>Готово</b>',

'LBL_IMPORT_CUSTOM_TITLE' => 'Многие приложения имеют возможность экспортировать данные в <b>Текстовый файл со значениями, разделенными запятой (.csv)</b> подобным образом:' ,
'LBL_CUSTOM_NUM_1' => 'Запуск приложения и открытие файла с данными' ,
'LBL_CUSTOM_NUM_2' => 'Выбор опции меню <b>Сохранить как...</b> или <b>Экспорт...</b>' ,
'LBL_CUSTOM_NUM_3' => 'Сохранение файла в формате <b>CSV</b> или <b>Значения, разделенные запятой</b>' ,
'LBL_IMPORT_TAB_TITLE' => 'Многие приложения имеют возможность экспортировать данные в формате <b>Табулированный текстовый файл (.tsv или .tab)</b> подобным образом:' ,
'LBL_TAB_NUM_1' => 'Запуск приложения и открытие файла с данными' ,
'LBL_TAB_NUM_2' => 'Выбор опции меню <b>Сохранить как...</b> или <b>Экспорт...</b>' ,
'LBL_TAB_NUM_3' => 'Сохранение файла в формате <b>TSV</b> или <b>Табулированные значения</b>' ,
'LBL_STEP_3_TITLE' => 'Шаг 3: Подтверждение и импорт' ,
'LBL_SELECT_FIELDS_TO_MAP' => 'В списке выберите поля, которые должны быть импортированы в систему. <br>По окончании нажмите кнопку <b>Начать импорт</b>.' ,
'LBL_DATABASE_FIELD' => 'Поля базы данных' ,
'LBL_HEADER_ROW' => 'Строка заголовков' ,
'LBL_ROW' => 'Строка' ,
'LBL_SAVE_AS_CUSTOM' => 'Сохранить пользовательскую схему импорта как:' ,
'LBL_SAVE_AS_CUSTOM_NAME' => 'Название пользовательской схемы импорта:',                              ///
'LBL_CONTACTS_NOTE_1' => 'Должна быть указана либо <b>Фамилия</b>, либо <b>Полное имя</b>.' ,
'LBL_CONTACTS_NOTE_2' => 'Если будет указано <b>Полное имя</b>, то поля <b>Имя</b> и <b>Фамилия</b> будут игнорироваться.' ,
'LBL_CONTACTS_NOTE_3' => 'Если будет указано <b>Полное имя</b>, то данные из этого поля будут разделены между полями <b>Имя</b> и <b>Фамилия</b> при вставке в базу данных.' ,
'LBL_CONTACTS_NOTE_4' => 'Поля <b>Улица 2</b> и <b>Улица 3</b> будут объединены вместе с основным адресным полем при вставке в базу данных.' ,
'LBL_ACCOUNTS_NOTE_1' => 'Поля <b>Улица 2</b> и <b>Улица 3</b> будут объединены вместе с основным адресным полем при вставке в базу данных.' ,
'LBL_REQUIRED_NOTE' => 'Обязательные поля: ',

//'LBL_OPPORTUNITIES_NOTE_1' => 'Поля <b>Имя сделки</b>, <b>Имя контрагента</b>, <b>Ожидаемая дата закрытия</b> и <b>Стадия продаж</b> являются обязательными для заполнения.' ,
'LBL_IMPORT_NOW' => 'Начать импорт' ,
'LBL_' => '' ,
'LBL_CANNOT_OPEN' => 'Не удается открыть файл для чтения' ,
'LBL_NOT_SAME_NUMBER' => 'Нет того же самого количества полей в строке Вашего файла' ,
'LBL_NO_LINES' => 'В импортируемом файле нет строк' ,
'LBL_FILE_ALREADY_BEEN_OR' => 'Импортируемый файл или уже обработан или не существует' ,
'LBL_SUCCESS' => 'Готово:' ,
'LBL_SUCCESSFULLY' => 'Импорт успешно завершен' ,
'LBL_LAST_IMPORT_UNDONE' => 'Ваше последнее импортирование отменено' ,
'LBL_NO_IMPORT_TO_UNDO' => 'Нечего отменять, т.к. ничего не импортировано.' ,
'LBL_FAIL' => 'Ошибка:' ,
'LBL_RECORDS_SKIPPED' => 'записи пропущены, так как пропущены одно или несколько обязательных полей' ,
'LBL_IDS_EXISTED_OR_LONGER' => 'записи пропущены, так как код или уже существует или его размер более 36 символов' ,
'LBL_RESULTS' => 'Результаты' ,
'LBL_IMPORT_MORE' => 'Импортировать ещё' ,
'LBL_FINISHED' => 'Возврат к модулю ' ,
'LBL_UNDO_LAST_IMPORT' => 'Отменить результаты импортирования' ,
'LBL_LAST_IMPORTED' => 'Созданные значения' ,
'ERR_MULTIPLE_PARENTS' => 'Вы можете определить только один родительский код' ,
'LBL_DUPLICATES' => 'Найдены дубликаты',
'LNK_DUPLICATE_LIST' => 'Загрузить список дубликатов',
'LNK_ERROR_LIST' => 'Загрузить список ошибок',
'LNK_RECORDS_SKIPPED_DUE_TO_ERROR' => 'Загрузить записи, которые не могут быть импортированы.',
'LBL_UNIQUE_INDEX' => 'Выберите индекс для сравнения дубликатов',
'LBL_VERIFY_DUPS' => 'Проверьте выбранные индексы на наличие повторяющихся значений.',
'LBL_INDEX_USED' => 'Используемые индексы:',
'LBL_INDEX_NOT_USED' => 'Неиспользуемые индексы:',
'LBL_IMPORT_MODULE_ERROR_NO_MOVE' => 'Файл не был загружен.  Проверьте права доступа к файлу в cache-директории SugarCRM.',

  'LBL_IMPORT_FIELDDEF_ID' => 'Уникальный ID',
    'LBL_IMPORT_FIELDDEF_RELATE' => 'Название или ID',
    'LBL_IMPORT_FIELDDEF_PHONE' => 'Номер телефона',
    'LBL_IMPORT_FIELDDEF_TEAM_LIST' => 'Team Name or ID',
    'LBL_IMPORT_FIELDDEF_NAME' => 'Любой текст',
    'LBL_IMPORT_FIELDDEF_VARCHAR' => 'Любой текст',
    'LBL_IMPORT_FIELDDEF_TEXT' => 'Любой текст',
    'LBL_IMPORT_FIELDDEF_TIME' => 'Время',
    'LBL_IMPORT_FIELDDEF_DATE' => 'Дата',
    'LBL_IMPORT_FIELDDEF_DATETIME' => 'Datetime',   ///
    'LBL_IMPORT_FIELDDEF_ASSIGNED_USER_NAME' => 'Имя пользователя или ID',
    'LBL_IMPORT_FIELDDEF_BOOL' => '\'0\' или \'1\'',
    'LBL_IMPORT_FIELDDEF_ENUM' => 'Список',
    'LBL_IMPORT_FIELDDEF_EMAIL' => 'Адрес E-Mail',
    'LBL_IMPORT_FIELDDEF_INT' => 'Цифра (только целое значение)',
    'LBL_IMPORT_FIELDDEF_DOUBLE' => 'Цифра (только целое значение)',
    'LBL_IMPORT_FIELDDEF_NUM' => 'Цифра (только целое значение)',
    'LBL_IMPORT_FIELDDEF_CURRENCY' => 'Цифра (допустимо дробное значение)',
    'LBL_IMPORT_FIELDDEF_FLOAT' => 'Цифра (допустимо дробное значение)',
    'LBL_DATE_FORMAT' => 'Формат даты:',
    'LBL_TIME_FORMAT' => 'Формат времени:',
    'LBL_TIMEZONE' => 'Часовой пояс:',
    'LBL_ADD_ROW' => 'Добавить поле',
    'LBL_REMOVE_ROW' => 'Удалить поле',
    'LBL_DEFAULT_VALUE' => 'Значение по умолчанию',
    'LBL_SHOW_ADVANCED_OPTIONS' => 'Показать дополнительные параметры',
    'LBL_HIDE_ADVANCED_OPTIONS' => 'Скрыть дополнительные параметры',
    'LBL_SHOW_PREVIEW_COLUMNS' => 'Show Preview Columns',    ///
    'LBL_HIDE_PREVIEW_COLUMNS' => 'Hide Preview Columns',     ///
    'LBL_SAVE_MAPPING_AS' => 'Сохранить схему импорта как',               ///
    'LBL_OPTION_ENCLOSURE_QUOTE' => 'Одинарная кавычка (\')',
    'LBL_OPTION_ENCLOSURE_DOUBLEQUOTE' => 'Двойная кавычка (")',
    'LBL_OPTION_ENCLOSURE_NONE' => 'Нет',
    'LBL_OPTION_ENCLOSURE_OTHER' => 'Другое:',
    'LBL_IMPORT_COMPLETE' => 'Завершение импорта',
    'LBL_IMPORT_ERROR' => 'В процессе импорта произошли ошибки',
    'LBL_IMPORT_RECORDS' => 'Импорт записей с',
    'LBL_IMPORT_RECORDS_OF' => 'из',
    'LBL_IMPORT_RECORDS_TO' => 'по',
    'LBL_CURRENCY' => 'Валюта',
	'LBL_CURRENCY_SIG_DIGITS' => 'Значащие цифры валюты',
	'LBL_LOCALE_EXAMPLE_NAME_FORMAT' => 'Пример',
    'LBL_NUMBER_GROUPING_SEP' => 'Символ разделителя разрядов',
    'LBL_DECIMAL_SEP' => 'Символ десятичного разделителя',
    'LBL_LOCALE_DEFAULT_NAME_FORMAT' => 'Формат имени по умолчанию',
    'LBL_LOCALE_EXAMPLE_NAME_FORMAT' => 'Пример',
    'LBL_LOCALE_NAME_FORMAT_DESC' => '<i>"s" Приветствие, "f" Имя, "l" Фамилия</i>',
    'LBL_CHARSET' => 'Кодировка',
    'LBL_MY_SAVED_HELP' => 'Сохраненные схемы импорта содержат ранее используемые правила импортирования данных, а также набор полей базы данных, в которые попадают данные из импортируемого файла.<br>Нажмите кнопку  <b>Опубликовать</b>, чтобы сделать схему импорта доступной для других пользователей.<br>Нажмите кнопку <b>Отменить публикацию</b>, чтобы сделать схему импорта недоступной для других пользователей.',
    'LBL_MY_PUBLISHED_HELP' => 'Опубликованные схемы импорта содержат ранее используемые правила импортирования данных, а также набор полей базы данных, в которые попадают данные из импортируемого файла.',
    'LBL_ENCLOSURE_HELP' => '<p><b>Ограничивающий символ</b> используется для разграничения содержимого полей, включая любые символы, которые используются в качестве разделителей.<br><br>Пример: Если в качестве разделителя используется запятая <b>(,)</b>, а в качестве ограничивающего символа используется двойная кавычка <b>(")</b>, то строка <br><b>"Токсово, Ленинградская область"</b> импортируется в одно поле в виде <b>Токсово, Ленинградская область</b>.<br>Если ограничивающие символы отсутствуют, или в качестве таковых используются другие символы, то строка <br><b>`Токсово, Ленинградская область`</b> импортируется в два соседних поля в виде <b>Токсово</b> и <b>Ленинградская область</b>.<br><br>Примечание: Импортируемый файл может не содержать ограничивающих символов.<br> В Excel для файлов, значения которых разделены точкой с запятой или символом табуляции, ограничивающим символом по умолчанию является двойная кавычка.</p>',
    'LBL_DELIMITER_COMMA_HELP' => 'Выберите эту опцию, если в качестве символа, разделяющего поля, используется <b>запятая</b>, или если в качестве расширения файла указано <b>.csv</b>.',
    'LBL_DELIMITER_TAB_HELP' => 'Выберите эту опцию, если в качестве символа, разделяющего поля, используется символ табуляции <b>(TAB)</b> и если в качестве расширения файла указано .txt.',
    'LBL_DELIMITER_CUSTOM_HELP' => 'Выберите эту опцию, если в качестве символа, разделяющего поля,  НЕ используется запятая или символ табуляции. Введите символ в расположенном рядом поле.',
    'LBL_DATABASE_FIELD_HELP' => 'Выберите необходимые поля из перечня всех существующих полей модуля.',
    'LBL_HEADER_ROW_HELP' => 'В первой строке импортируемого файла содержатся имена полей.',
    'LBL_DEFAULT_VALUE_HELP' => 'Значение по умолчанию для поля в создаваемой или обновляемой записи, если поле в файле импорта не содержит данных.',
    'LBL_ROW_HELP' => 'Это первая строка с данными импортируемого файла.',
    'LBL_SAVE_MAPPING_HELP' => 'Укажите название для набора полей базы данных, в которые попадают данные из импортируемого файла.<br>Набор полей базы данных, данные о сортировке полей, а также правила импортирования исходных данных, выбранные на первом шаге импорта будут сохранены при попытке импорта данных в систему.<br> Сохраненные схемы импорта  могут быть выбраны в дальнейшем на первом шаге процесса импортирования при необходимости импорта аналогичных данных.',
    'LBL_IMPORT_FILE_SETTINGS_HELP' => 'Укажите параметры импортируемого файла для того, чтобы данные были импортированы корректно. Эти параметры НЕ перезапишут ваши стандартные настройки. То есть при создании новых или обновлении существующих записей вновь будут учитываться настройки, указанные вами на странице <b>Мои  настройки</b>.',
    'LBL_IMPORT_FILE_SETTINGS' => 'Параметры импортируемого файла',
    'LBL_VERIFY_DUPLCATES_HELP' => 'Выберите поля в импортируемом файле, которые будут использоваться для проверки дубликатов.<br> Если данные в выбранных полях соответствуют данным в полях существующих записей, то из строк, содержащих дублирующиеся данные, НЕ будут созданы соответствующие записи.<br>Строки, содержащие поля с дублирующимися данными, будут указаны в отчёте о результатах импорта.',

	
	
	
    'LBL_IMPORT_STARTED' => 'Импорт начат',
    'LBL_RECORD_CANNOT_BE_UPDATED' => 'Недостаточно прав для обновления записи',

);

?>