<?php
if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');
/*********************************************************************************
 * SugarCRM is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004 - 2010 SugarCRM Inc.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo. If the display of the logo is not reasonably feasible for
 * technical reasons, the Appropriate Legal Notices must display the words
 * "Powered by SugarCRM".
 ********************************************************************************/

  /*********************************************************************************
  *
  * File generated by the RAPIRA Translation Suite ----------
  *
  ***********************************************************************likhobory*/

  /*********************************************************************************
  * Description : Defines the Russian language pack for the base application.
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s):
  *********************************************************************************/

$mod_strings = array (
	//module
'LBL_MODULE_NAME' => 'Документы' ,
'LBL_MODULE_TITLE' => 'Документы - ГЛАВНАЯ' ,
'LNK_NEW_DOCUMENT' => 'Создать документ' ,
'LNK_DOCUMENT_LIST' => 'Документы' ,
'LBL_DOC_REV_HEADER' => 'История' ,
'LBL_SEARCH_FORM_TITLE' => 'Поиск документа' ,
	//vardef labels
'LBL_DOCUMENT_ID' => 'Код документа' ,
'LBL_NAME' => 'Название документа' ,
'LBL_DESCRIPTION' => 'Описание' ,
'LBL_CATEGORY' => 'Категория' ,
'LBL_SUBCATEGORY' => 'Подкатегория' ,
'LBL_STATUS' => 'Статус' ,
'LBL_CREATED_BY' => 'Кем создано' ,
'LBL_DATE_ENTERED' => 'Дата ввода' ,
'LBL_DATE_MODIFIED' => 'Дата изменения' ,
'LBL_DELETED' => 'Удалено' ,
'LBL_MODIFIED' => 'Изменено (код)' ,
'LBL_MODIFIED_USER' => 'Изменено',
'LBL_CREATED' => 'Создано' ,
'LBL_REVISIONS'=>'Версии',
'LBL_RELATED_DOCUMENT_ID' => 'Код связанного документа' ,
'LBL_RELATED_DOCUMENT_REVISION_ID' => 'Код версии связанного документа' ,
'LBL_IS_TEMPLATE' => 'Шаблон?' ,
'LBL_TEMPLATE_TYPE' => 'Тип документа' ,
'LBL_ASSIGNED_TO_NAME'=>'Ответственный(ая):',
'LBL_REVISION_NAME' => 'Номер версии' ,
'LBL_MIME' => 'Тип MIME' ,
'LBL_REVISION' => 'Версия' ,
'LBL_DOCUMENT' => 'Связанные документы' ,
'LBL_LATEST_REVISION' => 'Последняя версия' ,
'LBL_CHANGE_LOG' => 'Журнал изменений:' ,
'LBL_ACTIVE_DATE' => 'Дата публикации' ,
'LBL_EXPIRATION_DATE' => 'Дата окончания' ,
'LBL_FILE_EXTENSION' => 'Расширение файла' ,
'LBL_LAST_REV_MIME_TYPE' => 'Последняя версия типа MIME',	
'LBL_CAT_OR_SUBCAT_UNSPEC' => 'Неопределенный' ,
	//quick search
'LBL_NEW_FORM_TITLE' => 'Новый документ',

	//document edit and detail view
'LBL_DOC_NAME' => 'Название документа:' ,
'LBL_FILENAME' => 'Имя файла:' ,
'LBL_DOC_VERSION' => 'Версия:' ,
'LBL_CATEGORY_VALUE' => 'Категория:' ,
'LBL_SUBCATEGORY_VALUE' => 'Подкатегория:' ,
'LBL_DOC_STATUS' => 'Статус:' ,
'LBL_LAST_REV_CREATOR' => 'Изменено:' ,
'LBL_LASTEST_REVISION_NAME' => 'Название последней версии:',
'LBL_SELECTED_REVISION_NAME' => 'Название выбранной версии:',
'LBL_CONTRACT_STATUS' => 'Contract status:', ///
'LBL_CONTRACT_NAME' => 'Contract name:', ///
'LBL_LAST_REV_DATE' => 'Дата изменения:' ,
'LBL_DOWNNLOAD_FILE' => 'Загрузить файл:' ,
'LBL_DET_RELATED_DOCUMENT'=>'Связанный документ:',
'LBL_DET_RELATED_DOCUMENT_VERSION'=>"Версия связанного документа:",
'LBL_DET_IS_TEMPLATE' => 'Шаблон? :' ,
'LBL_DET_TEMPLATE_TYPE' => 'Тип документа:' ,

'LBL_DOC_DESCRIPTION' => 'Описание:' ,
'LBL_DOC_ACTIVE_DATE' => 'Дата публикации:' ,
'LBL_DOC_EXP_DATE' => 'Актуален до:' ,
	
	//document list view.	
'LBL_LIST_FORM_TITLE' => 'Список документов' ,
'LBL_LIST_DOCUMENT' => 'Документ' ,
'LBL_LIST_CATEGORY' => 'Категория' ,
'LBL_LIST_SUBCATEGORY' => 'Подкатегория' ,
'LBL_LIST_REVISION' => 'Версия' ,
'LBL_LIST_LAST_REV_CREATOR' => 'Опубликовано' ,
'LBL_LIST_LAST_REV_DATE' => 'Дата изменения' ,
'LBL_LIST_VIEW_DOCUMENT' => 'Просмотр' ,
'LBL_LIST_DOWNLOAD'=> 'Загружено',
'LBL_LIST_ACTIVE_DATE' => 'Дата публикации' ,
'LBL_LIST_EXP_DATE' => 'Актуален до' ,
'LBL_LIST_STATUS' => 'Статус' ,
'LBL_LINKED_ID' => 'Id связанного документа',
'LBL_SELECTED_REVISION_ID' => 'Id выбранной версии',
'LBL_LATEST_REVISION_ID' => 'Id последней версии',
'LBL_SELECTED_REVISION_FILENAME' => 'Название выбранной версии',
'LBL_FILE_URL' => 'URL файла',
'LBL_REVISIONS_PANEL' => 'Описание версии',
'LBL_REVISIONS_SUBPANEL' => 'Версии',
	
	//document search form.
'LBL_SF_DOCUMENT' => 'Название документа:' ,
'LBL_SF_CATEGORY' => 'Категория:' ,
'LBL_SF_SUBCATEGORY' => 'Подкатегория:' ,
'LBL_SF_ACTIVE_DATE' => 'Дата публикации:' ,
'LBL_SF_EXP_DATE' => 'Актуален до:' ,
'DEF_CREATE_LOG' => 'Документ создан' ,
	
	//error messages
'ERR_DOC_NAME' => 'Название документа' ,
'ERR_DOC_ACTIVE_DATE' => 'Дата публикации' ,
'ERR_DOC_EXP_DATE' => 'Актуален до' ,
'ERR_FILENAME' => 'Имя файла' ,
'ERR_DOC_VERSION' => 'Версия документа' ,
'ERR_DELETE_CONFIRM' => 'Вы хотите удалить эту версию документа?' ,
'ERR_DELETE_LATEST_VERSION' => 'Вы не имеете права удалять последнюю версию документа.' ,
'LNK_NEW_MAIL_MERGE' => 'Слияние' ,
'LBL_MAIL_MERGE_DOCUMENT' => 'Шаблон слияния:' ,
'LBL_TREE_TITLE' => 'Документы' ,
	//sub-panel vardefs.
'LBL_LIST_DOCUMENT_NAME' => 'Название документа' ,
'LBL_CONTRACT_NAME' => 'Название договора:' ,
'LBL_LIST_IS_TEMPLATE' => 'Шаблон? :' ,
'LBL_LIST_TEMPLATE_TYPE' => 'Тип документа' ,
'LBL_LIST_SELECTED_REVISION' => 'Выбранная версия' ,
'LBL_LIST_LATEST_REVISION' => 'Последняя версия'  ,
'LBL_CONTRACTS_SUBPANEL_TITLE'=>'Связанные договоры',
'LBL_LAST_REV_CREATE_DATE'=>'Дата создания последней версии',
//'LNK_DOCUMENT_CAT'=>'Document Categories',
'LBL_CONTRACTS' => 'Договоры', 
'LBL_CREATED_USER' => 'Создано',
'LBL_THEREVISIONS_SUBPANEL_TITLE' => 'Возвраты',
'LBL_DOCUMENT_INFORMATION' => 'Описание документа',

);


?>