<?php
/*********************************************************************************
 * SugarCRM is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004 - 2010 SugarCRM Inc.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo. If the display of the logo is not reasonably feasible for
 * technical reasons, the Appropriate Legal Notices must display the words
 * "Powered by SugarCRM".
 ********************************************************************************/

  /*********************************************************************************
  *
  * File generated by the RAPIRA Translation Suite ----------
  *
  ***********************************************************************likhobory*/

  /*********************************************************************************
  * Description : Defines the Russian language pack for the base application.
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s):
  *********************************************************************************/

$mod_strings = array (
/*'ADMIN_EXPORT_ONLY' => 'Разрешить экспорт только администратору' ,*/
'ADVANCED' => 'Дополнительные настройки' ,

'DEFAULT_CURRENCY_ISO4217' => 'Код валюты - ISO 4217 ' ,
'DEFAULT_CURRENCY_NAME' => 'Название валюты' ,
'DEFAULT_CURRENCY_SYMBOL' => 'Символ валюты' ,
'DEFAULT_CURRENCY' => 'Валюта по умолчанию' ,
'DEFAULT_DATE_FORMAT' => 'Формат даты по умолчанию' ,
'DEFAULT_DECIMAL_SEP' => 'Десятичный разделитель' ,
'DEFAULT_LANGUAGE' => 'Язык по умолчанию' ,
'DEFAULT_NUMBER_GROUPING_SEP' => 'Символ разделителя разрядов' ,
'DEFAULT_SYSTEM_SETTINGS' => 'Пользовательский интерфейс' ,
'DEFAULT_THEME' => 'Тема по умолчанию' ,
'DEFAULT_TIME_FORMAT' => 'Формат времени по умолчанию' ,
/*'DISABLE_EXPORT' => 'Отключить экспорт' , */

'DISPLAY_RESPONSE_TIME' => 'Отображать время ответа сервера' ,
/*'EXPORT' => 'Экспорт' ,
'EXPORT_CHARSET' => 'Кодировка по умолчанию',
'EXPORT_DELIMITER' => 'Разделитель, используемый при экспорте',  */
'IMAGES' => 'Логотип' ,
'LBL_ADMIN_WIZARD' => 'Мастер настройки системы',
'LBL_ALLOW_USER_TABS' => 'Разрешить пользователям скрывать закладки',
'LBL_CONFIGURE_SETTINGS_TITLE' => 'Настройка конфигурации' ,
'LBL_ENABLE_MAILMERGE' => 'Включить слияние?' ,
'LBL_LOGVIEW' => 'Просмотр журнала' ,
'LBL_MAIL_SMTPAUTH_REQ' => 'Использовать SMTP-идентификацию?' ,
'LBL_MAIL_SMTPPASS' => 'SMTP-пароль:' ,
'LBL_MAIL_SMTPPORT' => 'SMTP-порт:' ,
'LBL_MAIL_SMTPSERVER' => 'SMTP-сервер:' ,
'LBL_MAIL_SMTPUSER' => 'SMTP-пользователь:' ,
'LBL_MAIL_SMTPTYPE'             => 'Тип SMTP-сервера:',
'LBL_MAIL_SMTP_SETTINGS'        => 'Настройка SMTP-сервера',
'LBL_CHOOSE_EMAIL_PROVIDER'     => 'Выберите почтовую службу:',
'LBL_YAHOOMAIL_SMTPPASS'		=> 'Yahoo! - пароль:',
'LBL_YAHOOMAIL_SMTPUSER'		=> 'Yahoo! - учетная запись почты:',
'LBL_GMAIL_SMTPPASS'			=> 'Gmail - пароль:',
'LBL_GMAIL_SMTPUSER'			=> 'Gmail - адрес:',
'LBL_EXCHANGE_SMTPPASS'			=> 'Exchange - пароль:',
'LBL_EXCHANGE_SMTPUSER'			=> 'Exchange - логин:',
'LBL_EXCHANGE_SMTPPORT'			=> 'Exchange - порт сервера:',
'LBL_EXCHANGE_SMTPSERVER'		=> 'Exchange  - сервер:',
'LBL_ALLOW_DEFAULT_SELECTION'   => 'Разрешить пользователям использовать данную учетную запись для отправки исходящей почты:',
'LBL_ALLOW_DEFAULT_SELECTION_HELP' => 'При выборе данной опции все пользователи смогут отправлять электронную почту (включая автоматические уведомления о назначении записей)<br>с использованием указанного здесь стандартного сервера исходящей почты.<br>В противном случае каждому пользователю при настройке учетной записи электронной почты необходимо вручную ввести настройки сервера исходящей почты.',

'LBL_MAILMERGE_DESC' => 'Этот флажок может быть установлен только при наличии соответствующего плагина для Microsoft&reg; Word&reg;.' ,
'LBL_MODULE_FAVICON'  => 'Отображать иконку модуля в качестве иконки сайта',
'LBL_MODULE_FAVICON_HELP' => 'Если вы находитесь в модуле, содержащем иконку, то эта иконка будет использоваться в качестве иконки сайта, вместо иконки сайта, содержащейся в текущей теме.',
'LBL_MAILMERGE' => 'Слияние' ,
'LBL_MODULE_NAME' => 'Настройка  конфигурации' ,
'LBL_MODULE_ID'  => 'Конфигуратор',
'LBL_MODULE_TITLE' => 'Пользовательский интерфейс' ,
'LBL_NOTIFY_FROMADDRESS' => 'С \\\" Адрес:' ,
'LBL_NOTIFY_SUBJECT' => 'Тема E-mail:' ,
'LBL_PORTAL_ON_DESC' => 'Allows users to manage portal user information within contact records. Portal users can access Cases, Bugs, Knowledge Base articles and other data through the Sugar Portal application.', ///
'LBL_PORTAL_ON' => 'Enable Portal User Management', ///
'LBL_PORTAL_TITLE' => 'Пользовательский портал' ,
'LBL_PROXY_AUTH' => 'Аутентификация?' ,
'LBL_PROXY_HOST' => 'Прокси-сервер' ,
'LBL_PROXY_ON_DESC' => 'Настройка прокси-сервера и параметров регистрации в системе' ,
'LBL_PROXY_ON' => 'Использовать прокси-сервер?' ,
'LBL_PROXY_PASSWORD' => 'Пароль' ,
'LBL_PROXY_PORT' => 'Порт' ,
'LBL_PROXY_TITLE' => 'Настройка прокси-сервера' ,
'LBL_PROXY_USERNAME' => 'Логин' ,
'LBL_RESTORE_BUTTON_LABEL' => 'Восстановить' ,
'LBL_SYSTEM_SETTINGS' => 'Настройка конфигурации',
'LBL_SKYPEOUT_ON_DESC' => 'Разрешать пользователям кликать на телефонных номерах с целью дозвона, используя SkypeOut&reg;.<br>  За дополнительной информацией обращайтесь к  Skype&reg; FAQ  ' ,
'LBL_SKYPEOUT_ON' => 'Включить интеграцию со SkypeOut&reg;' ,
'LBL_SKYPEOUT_TITLE' => 'SkypeOut&reg;' ,
'LBL_USE_REAL_NAMES' => 'Показывать полные имена пользователей',
'LBL_USE_REAL_NAMES_DESC' => 'Отображать полное имя пользователя вместо его логина.',
'LIST_ENTRIES_PER_LISTVIEW' => 'Количество отображаемых записей на странице' ,
'LIST_ENTRIES_PER_SUBPANEL' => 'Количество отображаемых субпанелей на странице' ,
'LOG_MEMORY_USAGE' => 'Вести журнал использования памяти' ,
'LOG_SLOW_QUERIES' => 'Вести журнал медленных запросов' ,
'LOCK_HOMEPAGE_HELP'=>'Данный параметр запрещает:<BR> 1) добавлять Разделы на главную страницу системы <BR>2) перемещать Разделы мышью на главной странице системы',



'CURRENT_LOGO' => 'Текущий логотип:' ,
'CURRENT_LOGO_HELP'=>'Данный логотип отображается в левом верхнем углу приложения.',
'NEW_LOGO' => 'Выбрать логотип' ,
'NEW_LOGO_HELP'=>'Допустимы следующие форматы изображений: PNG или JPG.<BR>Рекомендуемый размер изображения - 212x40 пикселей.',
'NEW_QUOTE_LOGO'=>'Upload new Quotes logo', ///
'NEW_QUOTE_LOGO_HELP'=>'The required image file format is .jpg.<BR>The recommended size is 867x74 px.', ///
'QUOTES_CURRENT_LOGO'=>'Quotes logo', ///
'SLOW_QUERY_TIME_MSEC' => 'Пороговое время выполнения медленных запросов (мсек) ' ,
'STACK_TRACE_ERRORS' => 'Отображать стековую трассировку ошибок' ,
'UPLOAD_MAX_SIZE' => 'Максимальный размер загружаемого файла' ,
'VERIFY_CLIENT_IP' => 'Проверка IP-адреса пользователя' ,
'LOCK_HOMEPAGE' => 'Запретить пользователям настройку главной страницы',
'LOCK_SUBPANELS' => 'Запретить пользователям настройку субпанелей',
'MAX_DASHLETS' => 'Максимальное количество Разделов на главной странице системы',
'SYSTEM_NAME' => 'Название системы:',
'SYSTEM_NAME_WIZARD'=>'Название:',
'SYSTEM_NAME_HELP'=>'Данное название отображается в заголовке браузера.',

    'LBL_LDAP_TITLE'=>'LDAP-аутентификация',
    'LBL_LDAP_ENABLE'=>'Включить LDAP',
    'LBL_LDAP_SERVER_HOSTNAME'=> 'Сервер:',
    'LBL_LDAP_SERVER_PORT'=> 'Порт:',
    'LBL_LDAP_ADMIN_USER'=> 'Имя пользователя:',
    'LBL_LDAP_ADMIN_USER_DESC'=>'Поиск пользователя Sugar. В случае отсутствия параметра будет выполнен анонимный вход.',
    'LBL_LDAP_ADMIN_PASSWORD'=> 'Пароль:',
    'LBL_LDAP_AUTHENTICATION'=> 'Аутентификация:',
	'LBL_LDAP_AUTHENTICATION_DESC'=>'Аутентификация на сервере LDAP, используя данные пользователя',
	'LBL_LDAP_AUTO_CREATE_USERS'=>'Автоматическое создание пользователей:',
    'LBL_LDAP_USER_DN'=>'DN пользователя:',
	'LBL_LDAP_GROUP_DN'=>'DN группы:',
	'LBL_LDAP_GROUP_DN_DESC'=>'Пример: <em>ou=groups,dc=example,dc=com</em>',
	'LBL_LDAP_USER_FILTER'=>'Параметры:',
	'LBL_LDAP_GROUP_MEMBERSHIP'=>'Членство в группе:',
	'LBL_LDAP_GROUP_MEMBERSHIP_DESC'=>'Пользователь должен быть членом определенной группы',
	'LBL_LDAP_GROUP_USER_ATTR'=>'Атрибут пользователя:',
	'LBL_LDAP_GROUP_USER_ATTR_DESC'=>'Уникальный идентификатор пользователя, используемый для проверки принадлежности пользователя к определенной группе, например: <em>uid</em>',
	'LBL_LDAP_GROUP_ATTR_DESC'=>'Уникальный Атрибут группы, например: <em>memberUid</em>',
	'LBL_LDAP_GROUP_ATTR'=>'Атрибут группы:',
	'LBL_LDAP_USER_FILTER_DESC'=>'Любые дополнительные параметры, применяемые в процессе аутентификации пользователей, например: <em>is_sugar_user=1 или (is_sugar_user=1)(is_sales=1)</em>',
    'LBL_LDAP_LOGIN_ATTRIBUTE'=>'Login-атрибут:',
    'LBL_LDAP_BIND_ATTRIBUTE'=>'Bind-атрибут:',
    'LBL_LDAP_BIND_ATTRIBUTE_DESC'=>'Аутентификация пользователя LDAP, например:[<b>AD:</b>&nbsp;userPrincipalName] [<b>openLDAP:</b>&nbsp;userPrincipalName] [<b>Mac&nbsp;OS&nbsp;X:</b>&nbsp;uid] ',
    'LBL_LDAP_LOGIN_ATTRIBUTE_DESC'=>'Поиск пользователя LDAP, например:[<b>AD:</b>&nbsp;userPrincipalName] [<b>openLDAP:</b>&nbsp;dn] [<b>Mac&nbsp;OS&nbsp;X:</b>&nbsp;dn] ',
    'LBL_LDAP_SERVER_HOSTNAME_DESC'=>'Пример: ldap.example.com или ldaps://ldap.example.com при включении SSL',
    'LBL_LDAP_SERVER_PORT_DESC'=>'Пример: 389 или 636 при включении SSL',
	'LBL_LDAP_GROUP_NAME'=>'Название группы:',
    'LBL_LDAP_GROUP_NAME_DESC'=>'Пример: <em>cn=sugarcrm</em>',
    'LBL_LDAP_USER_DN_DESC'=>'Пример: <em>ou=people,dc=example,dc=com</eM>',
    'LBL_LDAP_AUTO_CREATE_USERS_DESC'=> 'Если аутентифицированный пользователь не существует в базе Sugar, то он будет создан.',
    'LBL_LDAP_ENC_KEY' => 'Ключ шифрования:',
    'DEVELOPER_MODE' => 'Режим разработчика',
'LBL_LDAP_ENC_KEY_DESC' => 'Для SOAP-аутентификации при использовании LDAP.',
    'LDAP_ENC_KEY_NO_FUNC_DESC' => 'Расширение php_mcrypt должно быть включено в файле php.ini или же php должен быть скомпилирован с указанием соответствующего ключа.',
    'LBL_ALL' => 'Показать все',
    'LBL_MARK_POINT' => 'Установить контрольную точку',
    'LBL_NEXT_' => 'Далее>>',
    'LBL_REFRESH_FROM_MARK' => 'Обновить с контр. точки',   
    'LBL_SEARCH' => 'Найти:',
    'LBL_REG_EXP' => 'RegExp:',
    'LBL_IGNORE_SELF' => 'Ignore Self:',   /// не исп.
    'LBL_MARKING_WHERE_START_LOGGING'=>'Контрольная точка в журнале установлена',   
    'LBL_DISPLAYING_LOG'=>'Результат:',   
    'LBL_YOUR_PROCESS_ID'=>'ID процесса:',
    'LBL_YOUR_IP_ADDRESS'=>'Ваш IP-адрес:',
    'LBL_IT_WILL_BE_IGNORED'=>' it will be ignored ',   ///
    'LBL_LOG_NOT_CHANGED'=>' Журнал не был изменен',      
    'LBL_ALERT_JPG_IMAGE' => 'Файл изображения должен быть в формате JPEG. Загрузите новый файл с расширением .jpg.',
    'LBL_ALERT_TYPE_IMAGE' => 'Файл изображения должен быть в формате JPEG или PNG. Загрузите новый файл с расширением .jpg или .png.',
    'LBL_ALERT_SIZE_RATIO' => 'Соотношение сторон изображения должно быть между 1:1 и 10:1. Размер изображения будет изменен.',
    'LBL_ALERT_SIZE_RATIO_QUOTES' => 'Соотношение сторон изображения должно быть между 3:1 и 20:1. Загрузите новый файл.',
     'ERR_ALERT_FILE_UPLOAD' => 'Произошла ошибка в процессе загрузки изображения.',
     'LBL_LOGGER'=>'Параметры журнала',
	'LBL_LOGGER_FILENAME'=>'Имя файла журнала:',
	'LBL_LOGGER_FILE_EXTENSION'=>'Расширение:',
	'LBL_LOGGER_MAX_LOG_SIZE'=>'Максимальный размер файла журнала:',
	'LBL_LOGGER_DEFAULT_DATE_FORMAT'=>'Формат даты по умолчанию:',
	'LBL_LOGGER_LOG_LEVEL'=>'Уровень детализации:',
	'LBL_LOGGER_MAX_LOGS'=>'Максимальное количество файлов журнала:',
	'LBL_LOGGER_FILENAME_SUFFIX' =>'Дополнительный суффикс имени файла журнала:',
	'LBL_VCAL_PERIOD' => 'Параметры доступности vCal:',
	'vCAL_HELP' => 'Используйте этот параметр для указания количества месяцев, в течение которых возможна публикация данных о занятости (звонки и встречи) из календаря.<BR>При включенной публикации допустимы значения от 1 до 12 месяцев. Для выключения возможности публикации введите "0".',



	
	
	
	
	'LBL_PDFMODULE_NAME' => 'PDF Settings',
    'SUGARPDF_BASIC_SETTINGS' => 'Document Properties',
    'SUGARPDF_ADVANCED_SETTINGS' => 'Advanced Settings',
    'SUGARPDF_LOGO_SETTINGS' => 'Images',

    'PDF_CREATOR' => 'PDF Creator',
    'PDF_CREATOR_INFO' => 'Defines the creator of the document. <br>This is typically the name of the application that generates the PDF.',

    'PDF_AUTHOR' => 'Author',
    'PDF_AUTHOR_INFO' => 'The Author appears in the document properties.',

    'PDF_HEADER_LOGO' => 'For Quotes PDF Documents',
    'PDF_HEADER_LOGO_INFO' => 'This image appears in the default Header in Quotes PDF Documents.',

    'PDF_NEW_HEADER_LOGO' => 'Select New Image for Quotes',
    'PDF_NEW_HEADER_LOGO_INFO' => 'The file format can be either .jpg or .png. (Only .jpg for EZPDF)<BR>The recommended size is 867x74 px.',

    'PDF_HEADER_LOGO_WIDTH' => 'Quotes Image Width',
    'PDF_HEADER_LOGO_WIDTH_INFO' => 'Change the scale of the uploaded image that appears in Quotes PDF Documents. (TCPDF only)',

    'PDF_SMALL_HEADER_LOGO' => 'For Reports PDF Documents',
    'PDF_SMALL_HEADER_LOGO_INFO' => 'This image appears in the default Header in Reports PDF Documents.<br> This image also appears in the top left-hand corner of the Sugar application.',

    'PDF_NEW_SMALL_HEADER_LOGO' => 'Select New Image for Reports',
    'PDF_NEW_SMALL_HEADER_LOGO_INFO' => 'The file format can be either .jpg or .png. (Only .jpg for EZPDF)<BR>The recommended size is 212x40 px.',

    'PDF_SMALL_HEADER_LOGO_WIDTH' => 'Reports Image Width',
    'PDF_SMALL_HEADER_LOGO_WIDTH_INFO' => 'Change the scale of the uploaded image that appears in Reports PDF Documents. (TCPDF only)',


    'PDF_HEADER_STRING' => 'Header String',
    'PDF_HEADER_STRING_INFO' => 'Header description string',

    'PDF_HEADER_TITLE' => 'Header Title',
    'PDF_HEADER_TITLE_INFO' => 'String to print as title on document header',

    'PDF_FILENAME' => 'Default Filename',
    'PDF_FILENAME_INFO' => 'Default filename for the generated PDF files',

    'PDF_TITLE' => 'Title',
    'PDF_TITLE_INFO' => 'The Title appears in the document properties.',

    'PDF_SUBJECT' => 'Subject',
    'PDF_SUBJECT_INFO' => 'The Subject appears in the document properties.',

    'PDF_KEYWORDS' => 'Keyword(s)',
    'PDF_KEYWORDS_INFO' => 'Associate Keywords with the document, generally in the form "keyword1 keyword2..."',

    'PDF_COMPRESSION' => 'Compression',
    'PDF_COMPRESSION_INFO' => 'Activates or deactivates page compression. <br>When activated, the internal representation of each page is compressed, which leads to a compression ratio of about 2 for the resulting document.',

    'PDF_JPEG_QUALITY' => 'JPEG Quality (1-100)',
    'PDF_JPEG_QUALITY_INFO' => 'Set the default JPEG compression quality (1-100)',

    'PDF_PDF_VERSION' => 'PDF Version',
    'PDF_PDF_VERSION_INFO' => 'Set the PDF version (check PDF reference for valid values).',

    'PDF_PROTECTION' => 'Document Protection',
    'PDF_PROTECTION_INFO' => 'Set document protection<br>- copy: copy text and images to the clipboard<br>- print: print the document<br>- modify: modify it (except for annotations and forms)<br>- annot-forms: add annotations and forms<br>Note: the protection against modification is for people who have the full Acrobat product.',

    'PDF_USER_PASSWORD' => 'User Password',
    'PDF_USER_PASSWORD_INFO' => 'If you don\\\'t set any password, the document will open as usual. <br>If you set a user password, the PDF viewer will ask for it before displaying the document. <br>The master password, if different from the user one, can be used to get full access.',

    'PDF_OWNER_PASSWORD' => 'Owner Password',
    'PDF_OWNER_PASSWORD_INFO' => 'If you don\\\'t set any password, the document will open as usual. <br>If you set a user password, the PDF viewer will ask for it before displaying the document. <br>The master password, if different from the user one, can be used to get full access.',
    
    'PDF_ACL_ACCESS' => 'Access Control',
    'PDF_ACL_ACCESS_INFO' => 'Default Access Control for the PDF generation.',

    'K_CELL_HEIGHT_RATIO' => 'Cell Height Ratio',
    'K_CELL_HEIGHT_RATIO_INFO' => 'If the height of a cell is smaller than (Font Height x Cell Height Ratio), then (Font Height x Cell Height Ratio) is used as the cell height.<br>(Font Height x Cell Height Ratio) is also used as the height of the cell when no height is define.',

    'K_TITLE_MAGNIFICATION' => 'Title Magnification',
    'K_TITLE_MAGNIFICATION_INFO' => 'Title magnification respect main font size.',

    'K_SMALL_RATIO' => 'Small Font Factor',
    'K_SMALL_RATIO_INFO' => 'Reduction factor for small font.',

    'HEAD_MAGNIFICATION' => 'Head Magnification',
    'HEAD_MAGNIFICATION_INFO' => 'Magnification factor for titles.',

    'PDF_IMAGE_SCALE_RATIO' => 'Image scale ratio',
    'PDF_IMAGE_SCALE_RATIO_INFO' => 'Ratio used to scale the images',

    'PDF_UNIT' => 'Unit',
    'PDF_UNIT_INFO' => 'document unit of measure',
	'PDF_GD_WARNING'=>'You do not have the GD library installed for PHP. Without the GD library installed, only JPEG logos can be displayed in PDF documents.',
    'ERR_EZPDF_DISABLE'=>'Warning : The EZPDF class is disabled from the config table and it set as the PDF class. Please "Save" this form to set TCPDF as the PDF Class and return in a stable state.',
    'LBL_IMG_RESIZED'=>"(resized for display)",


    'LBL_FONTMANAGER_BUTTON' => 'PDF Font Manager',
    'LBL_FONTMANAGER_TITLE' => 'PDF Font Manager',
    'LBL_FONT_BOLD' => 'Bold',
    'LBL_FONT_ITALIC' => 'Italic',
    'LBL_FONT_BOLDITALIC' => 'Bold/Italic',
    'LBL_FONT_REGULAR' => 'Regular',

    'LBL_FONT_TYPE_CID0' => 'CID-0',
    'LBL_FONT_TYPE_CORE' => 'Core',
    'LBL_FONT_TYPE_TRUETYPE' => 'TrueType',
    'LBL_FONT_TYPE_TYPE1' => 'Type1',
    'LBL_FONT_TYPE_TRUETYPEU' => 'TrueTypeUnicode',

    'LBL_FONT_LIST_NAME' => 'Name',
    'LBL_FONT_LIST_FILENAME' => 'Filename',
    'LBL_FONT_LIST_TYPE' => 'Type',
    'LBL_FONT_LIST_STYLE' => 'Style',
    'LBL_FONT_LIST_STYLE_INFO' => 'Style of the font',
    'LBL_FONT_LIST_ENC' => 'Encoding',
    'LBL_FONT_LIST_EMBEDDED' => 'Embedded',
    'LBL_FONT_LIST_EMBEDDED_INFO' => 'Check to embed the font into the PDF file',
    'LBL_FONT_LIST_CIDINFO' => 'CID Information',
    'LBL_FONT_LIST_CIDINFO_INFO' => "Examples :".
"<ul><li>".
"Chinese Traditional :<br>".
"<pre>\$enc=\'UniCNS-UTF16-H\';<br>".
"\$cidinfo=array(\'Registry\'=>\'Adobe\', \'Ordering\'=>\'CNS1\',\'Supplement\'=>0);<br>".
"include(\'include/tcpdf/fonts/uni2cid_ac15.php\');</pre>".
"</li><li>".
"Chinese Simplified :<br>".
"<pre>\$enc=\'UniGB-UTF16-H\';<br>".
"\$cidinfo=array(\'Registry\'=>\'Adobe\', \'Ordering\'=>\'GB1\',\'Supplement\'=>2);<br>".
"include(\'include/tcpdf/fonts/uni2cid_ag15.php\');</pre>".
"</li><li>".
"Korean :<br>".
"<pre>\$enc=\'UniKS-UTF16-H\';<br>".
"\$cidinfo=array(\'Registry\'=>\'Adobe\', \'Ordering\'=>\'Korea1\',\'Supplement\'=>0);<br>".
"include(\'include/tcpdf/fonts/uni2cid_ak12.php\');</pre>".
"</li><li>".
"Japanese :<br>".
"<pre>\$enc=\'UniJIS-UTF16-H\';<br>".
"\$cidinfo=array(\'Registry\'=>\'Adobe\', \'Ordering\'=>\'Japan1\',\'Supplement\'=>5);<br>".
"include(\'include/tcpdf/fonts/uni2cid_aj16.php\');</pre>".
"</li></ul>".
"More help : www.tcpdf.org",
    'LBL_FONT_LIST_FILESIZE' => 'Font Size (KB)',
    'LBL_ADD_FONT' => 'Add a font',
    'LBL_BACK' => 'Back',
    'LBL_REMOVE' => 'rem',
    'LBL_JS_CONFIRM_DELETE_FONT' => 'Are you sure that you want to delete this font?',

    'LBL_ADDFONT_TITLE' => 'Add a PDF Font',
    'LBL_PDF_PATCH' => 'Patch',
    'LBL_PDF_PATCH_INFO' => 'Custom modification of the encoding. Write a PHP array.<br>Example :<br>ISO-8859-1 does not contain the euro symbol. To add it at position 164, write "array(164=>\\\'Euro\\\')".',
    'LBL_PDF_ENCODING_TABLE' => 'Encoding Table',
    'LBL_PDF_ENCODING_TABLE_INFO' => 'Name of the encoding table.<br>This option is ignored for TrueType Unicode, OpenType Unicode and symbolic fonts.<br>The encoding defines the association between a code (from 0 to 255) and a character contained in the font.<br>The first 128 are fixed and correspond to ASCII.',
    'LBL_PDF_FONT_FILE' => 'Font File',
    'LBL_PDF_FONT_FILE_INFO' => '.ttf or .otf or .pfb file',
    'LBL_PDF_METRIC_FILE' => 'Metric File',
    'LBL_PDF_METRIC_FILE_INFO' => '.afm or .ufm file',
    'LBL_ADD_FONT_BUTTON' => 'Add',
    'JS_ALERT_PDF_WRONG_EXTENSION' => 'This file do not have a good file extension.',
    'LBL_PDF_INSTRUCTIONS' => 'Instructions',
    'PDF_INSTRUCTIONS_ADD_FONT' => <<<BSOFR
Fonts supported by SugarPDF :
<ul>
<li>TrueTypeUnicode (UTF-8 Unicode)</li>
<li>OpenTypeUnicode</li>
<li>TrueType</li>
<li>OpenType</li>
<li>Type1</li>
<li>CID-0</li>
</ul>
<br>
If you choose to not embed your font in the PDF, the generated PDF file will be lighter but a substitution will be use if the font is not available in the system of your reader.
<br><br>
Adding a PDF font to SugarCRM requires to follow steps 1 and 2 of the TCPDF Fonts documentation available in the "DOCS" section of the <a href="http://www.tcpdf.org" target="_blank">TCPDF website</a>.
<br><br>The pfm2afm and ttf2ufm utils are available in fonts/utils in the TCPDF package that you can download on the "DOWNLOAD" section of the <a href="http://www.tcpdf.org" target="_blank">TCPDF website</a>.
<br><br>Load the metric file generated in step 2 and your font file below.
BSOFR
,
    'ERR_MISSING_CIDINFO' => 'The field CID Information cannot be empty.',
    'LBL_ADDFONTRESULT_TITLE' => 'Result of the add font process',
    'LBL_STATUS_FONT_SUCCESS' => 'SUCCESS : The font has been added to SugarCRM.',
    'LBL_STATUS_FONT_ERROR' => 'ERROR : The font has not been added. Look at the log below.',
    'LBL_FONT_MOVE_DEFFILE' => 'Font definition file move to : ',
    'LBL_FONT_MOVE_FILE' => 'Font file move to : ',

// Font manager
    'ERR_LOADFONTFILE' => 'ERROR: LoadFontFile error!',
    'ERR_FONT_EMPTYFILE' => 'ERROR: Empty filename!',
    'ERR_FONT_UNKNOW_TYPE' => 'ERROR: Unknow font type:',
    'ERR_DELETE_CORE_FILE' => 'ERROR: It is not possible to delete a core font.',
    'ERR_NO_FONT_PATH' => 'ERROR: No font path available!',
    'ERR_NO_CUSTOM_FONT_PATH' => 'ERROR: No custom font path available!',
    'ERR_FONT_NOT_WRITABLE' => 'is not writable.',
    'ERR_FONT_FILE_DO_NOT_EXIST' => 'doesn\'t exist or is not a directory.',
    'ERR_FONT_MAKEFONT' => 'ERROR: MakeFont error',
    'ERR_FONT_ALREADY_EXIST' => 'ERROR : This font already exist. Rollback...',
    'ERR_PDF_NO_UPLOAD' => 'Error during the upload of the font or metric file.',
	
// Wizard
    'LBL_WIZARD_TITLE' => 'Мастер настройки параметров SugarCRM',
    'LBL_WIZARD_WELCOME_TAB' => 'Добро пожаловать',
    'LBL_WIZARD_WELCOME_TITLE' => 'Добро пожаловать в Sugar!',

    'LBL_WIZARD_WELCOME' => 'Предлагаем вам настроить параметры системы.<br /><br /> 
Мастер настройки содержит три страницы:<br />
&bull;&nbsp;На первой странице вы можете настроить логотип вашей организации.<br />
&bull;&nbsp;На второй странице вы можете сконфигурировать региональные настройки системы.<br />
&bull;&nbsp;На третьей странице вы можете настроить параметры сервера исходящей почты.<br />
<br />
По завершении работы мастера вы сможете настроить параметры собственной учетной записи и приступить к работе в системе.<br /><br />
Если вы хотите настроить параметры системы позже, нажмите на кнопку <b>Пропустить</b>.',
    'LBL_WIZARD_NEXT_BUTTON' => 'Вперед >',
    'LBL_WIZARD_BACK_BUTTON' => '< Назад',
	'LBL_WIZARD_SKIP_BUTTON' => 'Пропустить',
    'LBL_WIZARD_FINISH_BUTTON' => 'Готово',
    'LBL_WIZARD_CONTINUE_BUTTON' => 'Продолжить',
    'LBL_WIZARD_FINISH_TAB' => 'Готово',
    'LBL_WIZARD_FINISH_TITLE' => 'Настройка основных параметров системы завершена',
    'LBL_WIZARD_FINISH' => 'Нажмите на кнопку <b>Продолжить</b> для настройки учетной записи.<br/><br />
Для настройки дополнительных параметров системы нажмите <a href="index.php?module=Administration&action=index" target="_blank">здесь</a>.<br /><br />Ищете справочную информацию по работе в системе?<br /><br />Посетите <a  href="http://www.sugarcrm.com.ua/viewforum.php?f=5&sid=22ab9852049e1b3ae9ba9b6c46cff6aa" target="_blank">русскоязычный форум, посвященный SugarCRM</a>, для получения русскоязычной документации, а также <a href="http://support.sugarcrm.com" target="_blank">сайт поддержки SugarCRM</a>   для:<br /><br />
&bull;&nbsp;Ознакомления с <a href="http://www.sugarcrm.com/crm/support/documentation" target="_blank">англоязычной документацией</a><br />
&bull;&nbsp;Нахождения решения возможных проблем в  <a href="http://kb.sugarcrm.com/" target="_blank">базе знаний</a><br />
&bull;&nbsp;Доступа к <a href="http://www.sugarcrm.com/university/" target="_blank">учебным материалам</a><br />',
    'LBL_WIZARD_SYSTEM_TITLE' => 'Настройка логотипа',
    'LBL_WIZARD_SYSTEM_DESC' => 'Укажите название вашей организации и выберите логотип.',
    'LBL_WIZARD_LOCALE_DESC' => 'Укажите каким образом должны быть представлены данные в системе. Указанные здесь параметры будут являться параметрами по умолчанию. В дальнейшем пользователи смогут изменить данные параметры по своему усмотрению.',
    'LBL_WIZARD_SMTP_DESC' => 'Учетная запись исходящей почты будет использоваться для отправки исходящей почты, в том числе такой как уведомления о назначении ответственного, а также писем с информацией о новом пароле. Электронный адрес данной учетной записи будет фигурировать в получаемых письмах в качестве отправителя.',
'LBL_MOBILE_MOD_REPORTS_RESTRICTION' => '* The Reports module is only available for the Sugar Mobile iPhone client.', ///

);



?>
