<?php
if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');
/*********************************************************************************
 * SugarCRM is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004 - 2010 SugarCRM Inc.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo. If the display of the logo is not reasonably feasible for
 * technical reasons, the Appropriate Legal Notices must display the words
 * "Powered by SugarCRM".
 ********************************************************************************/


  /*********************************************************************************
  *
  * File generated by the RAPIRA Translation Suite ----------
  *
  ***********************************************************************likhobory*/

  /*********************************************************************************
  * Description : Defines the Russian language pack for the base application.
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s):
  *********************************************************************************/

$mod_strings = array (
'LBL_MODULE_NAME' => 'Календарь' ,
'LBL_MODULE_TITLE' => 'Календарь' ,
'LBL_MODULE_ACTION'=>'Мероприятия',
'LNK_NEW_CALL' => 'Назначить звонок' ,
'LNK_NEW_MEETING' => 'Назначить встречу' ,
'LNK_NEW_APPOINTMENT' => 'Назначить встречу/звонок' ,
'LNK_NEW_TASK' => 'Создать задачу' ,
'LNK_CALL_LIST' => 'Звонки' ,
'LNK_MEETING_LIST' => 'Встречи' ,
'LNK_TASK_LIST' => 'Задачи' ,
'LNK_VIEW_CALENDAR' => 'Сегодня' ,
'LNK_IMPORT_CALLS'=>'Импорт звонков',
'LNK_IMPORT_MEETINGS'=>'Импорт встреч',
'LNK_IMPORT_TASKS'=>'Импорт задач',
'LBL_MONTH' => 'Месяц' ,
'LBL_DAY' => 'День' ,
'LBL_YEAR' => 'Год' ,
'LBL_WEEK' => 'Неделя' ,
'LBL_PREVIOUS_MONTH' => 'Предыдущий месяц' ,
'LBL_PREVIOUS_DAY' => 'Предыдущий день' ,
'LBL_PREVIOUS_YEAR' => 'Предыдущий год' ,
'LBL_PREVIOUS_WEEK' => 'Предыдущая неделя' ,
'LBL_NEXT_MONTH' => 'Следующий месяц' ,
'LBL_NEXT_DAY' => 'Следующий день' ,
'LBL_NEXT_YEAR' => 'Следующий год' ,
'LBL_NEXT_WEEK' => 'Следующая неделя' ,
'LBL_AM' => 'AM',
'LBL_PM' => 'PM',
'LBL_SCHEDULED' => 'Запланировано' ,
'LBL_BUSY' => 'Занято' ,
'LBL_CONFLICT' => 'Конфликт' ,
'LBL_USER_CALENDARS' => 'Пользовательские календари' ,
'LBL_SHARED' => 'Сводный' ,
'LBL_PREVIOUS_SHARED' => 'Пред.' ,
'LBL_NEXT_SHARED' => 'След.' ,
'LBL_SHARED_CAL_TITLE' => 'Сводный календарь' ,
'LBL_USERS' => 'Пользователь' ,
'LBL_REFRESH' => 'Обновить' ,
'LBL_EDIT' => 'Править' ,
'LBL_SELECT_USERS' => 'Выбор пользователей для просмотра календаря' ,
'LBL_FILTER_BY_TEAM' => 'Фильтрация списка пользователей по группам:' ,
'LBL_ASSIGNED_TO_NAME' => 'Ответственный(ая)',
'LBL_DATE' => 'Начальные дата и время'

);

$mod_list_strings = array (
  'dom_cal_weekdays' => array (
      'Вс' ,
      'Пн' ,
      'Вт' ,
      'Ср' ,
      'Чт' ,
      'Пт' ,
      'Сб' ,
       ),
   'dom_cal_weekdays_long' => array (
      'Воскресенье' ,
      'Понедельник' ,
      'Вторник' ,
      'Среда' ,
      'Четверг' ,
      'Пятница' ,
      'Суббота' ,
        ),
      
   'dom_cal_month' => array (
      '' ,
      'Янв' ,
      'Фев' ,
      'Мар' ,
      'Апр' ,
      'Май' ,
      'Июн' ,
      'Июл' ,
      'Авг' ,
      'Сен' ,
      'Окт' ,
      'Ноя' ,
      'Дек' ,
        ),
   'dom_cal_month_long' => array (
      '' ,
      'Январь' ,
      'Февраль' ,
      'Март' ,
      'Апрель' ,
      'Май' ,
      'Июнь' ,
      'Июль' ,
      'Август' ,
      'Сентябрь' ,
      'Октябрь' ,
      'Ноябрь' ,
      'Декабрь' ,
        )

      );
?>