<?PHP
/*********************************************************************************
 * SugarCRM is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2010 SugarCRM Inc.
 * 
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 * 
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 * 
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 * 
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 * 
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo. If the display of the logo is not reasonably feasible for
 * technical reasons, the Appropriate Legal Notices must display the words
 * "Powered by SugarCRM".
 ********************************************************************************/
/**
 * THIS CLASS IS GENERATED BY MODULE BUILDER
 * PLEASE DO NOT CHANGE THIS CLASS
 * PLACE ANY CUSTOMIZATIONS IN sphr_Client
 */

require_once('include/SugarObjects/templates/person/Person.php');

class sphr_Client_sugar extends Person {
	var $new_schema = true;
	var $module_dir = 'sphr_Client';
	var $object_name = 'sphr_Client';
	var $table_name = 'sphr_client';
	var $importable = true;
	var $disable_row_level_security = true ; // to ensure that modules created and deployed under CE will continue to function under team security if the instance is upgraded to PRO
		var $id;
		var $name;
		var $date_entered;
		var $date_modified;
		var $modified_user_id;
		var $modified_by_name;
		var $created_by;
		var $created_by_name;
		var $description;
		var $deleted;
		var $created_by_link;
		var $modified_user_link;
		var $assigned_user_id;
		var $assigned_user_name;
		var $assigned_user_link;
		var $salutation;
		var $first_name;
		var $last_name;
		var $full_name;
		var $title;
		var $department;
		var $do_not_call;
		var $phone_home;
		var $phone_mobile;
		var $phone_work;
		var $phone_other;
		var $phone_fax;
		var $email1;
		var $email2;
		var $invalid_email;
		var $email_opt_out;
		var $primary_address_street;
		var $primary_address_street_2;
		var $primary_address_street_3;
		var $primary_address_city;
		var $primary_address_state;
		var $primary_address_postalcode;
		var $primary_address_country;
		var $alt_address_street;
		var $alt_address_street_2;
		var $alt_address_street_3;
		var $alt_address_city;
		var $alt_address_state;
		var $alt_address_postalcode;
		var $alt_address_country;
		var $assistant;
		var $assistant_phone;
		var $email_addresses_primary;
		var $email_addresses;
		var $address_post;
		var $status_description;
		var $passport_type;
		var $passport_series;
		var $passport_number;
		var $source;
		var $status;
		var $passport_foreigner_ser_and_num;
		var $passport_issue_date;
		var $passport_issued;
		var $address_temporary;
		var $address_permanent;
		var $address_actual;
		var $addressl_actual;
		var $addressl_legal;
		var $phone;
		var $inn_and_kpp;
		var $account_and_bank;
		var $name_general_director;
		var $email;
		var $last_and_middle_name;
		var $passport_first_name;
		var $passport_last_name;
		var $passport_middle_name;
		function sphr_Client_sugar(){	
		parent::Person();
	}
	
	function bean_implements($interface){
		switch($interface){
			case 'ACL': return true;
		}
		return false;
}

    // this is the method which constructs the default SQL query
    function create_new_list_query($order_by, $where, $filter, $params, $show_deleted, $join_type, $return_array, $parentbean, $singleSelect){
        // call the parent method to populate all params - will cause errors/problems elsewhere otherwise
        $ret_array = parent::create_new_list_query($order_by, $where,$filter,$params, $show_deleted,$join_type, $return_array,$parentbean, $singleSelect);

        $sql_activitiesa = "
            SELECT
              (SELECT count(t.id) FROM tasks t WHERE t.parent_id = sphr_client.id AND status <> 'Completed') +
              (SELECT count(m.id) FROM meetings m WHERE m.parent_id = sphr_client.id AND status = 'Planned') +
              (SELECT count(c.id) FROM calls c WHERE c.parent_id = sphr_client.id AND status = 'Planned')
              as activities,
            ";
        $ret_array["select_old"] = $ret_array['select'];
        $ret_array['select'] = str_replace(' SELECT', $sql_activitiesa, $ret_array['select']);
        

        return $ret_array;
    }

		
}
?>