<?php
/*********************************************************************************
 * SugarCRM is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2010 SugarCRM Inc.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo. If the display of the logo is not reasonably feasible for
 * technical reasons, the Appropriate Legal Notices must display the words
 * "Powered by SugarCRM".
 ********************************************************************************/
$dictionary['sphr_Client'] = array(
	'table'=>'sphr_client',
	'audited'=>true,
	'fields'=>array (
  'address_post' =>
  array (
    'required' => false,
    'name' => 'address_post',
    'vname' => 'LBL_ADDRESS_POST',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => '255',
    'size' => '20',
  ),
  'status_description' =>
  array (
    'name' => 'status_description',
    'vname' => 'LBL_STATUS_DESCRIPTION',

    'required' => false,
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,

	'type' => 'text',
   	'rows' => '10',
	'cols' =>'100',
	/*
	'type' => 'varchar',
    'len' => '255',
    'size' => '20',
	*/
  ),
  'passport_type' =>
  array (
    'required' => false,
    'name' => 'passport_type',
    'vname' => 'LBL_PASSPORT_TYPE',
    'type' => 'enum',
    'massupdate' => 0,
    'default' => 'russian',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => 100,
    'size' => '20',
    'options' => 'passport_type_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'passport_series' =>
  array (
    'required' => false,
    'name' => 'passport_series',
    'vname' => 'LBL_PASSPORT_SERIES',
    'type' => 'int',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => '4',
    'size' => '20',
    'disable_num_format' => '',
  ),
  'passport_number' =>
  array (
    'required' => true,
    'name' => 'passport_number',
    'vname' => 'LBL_PASSPORT_NUMBER',
    'type' => 'int',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => '6',
    'size' => '20',
    'disable_num_format' => '',
  ),
  'source' =>
  array (
    'required' => false,
    'name' => 'source',
    'vname' => 'LBL_SOURCE',
    'type' => 'enum',
    'massupdate' => 0,
    'default' => 'mk1',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => 100,
    'size' => '20',
    'options' => 'client_source_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'status' =>
  array (
    'required' => false,
    'name' => 'status',
    'vname' => 'LBL_STATUS',
    'type' => 'enum',
    'massupdate' => 0,
    'default' => 'status_1',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => 100,
    'size' => '20',
    'options' => 'client_status_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'passport_foreigner_ser_and_num' =>
  array (
    'required' => false,
    'name' => 'passport_foreigner_ser_and_num',
    'vname' => 'LBL_PASSPORT_FOREIGNER_SER_AND_NUM',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => '255',
    'size' => '20',
  ),
  'first_name' =>
  array (
    'name' => 'first_name',
    'vname' => 'LBL_FIRST_NAME',
    'type' => 'varchar',
    'len' => '255',
    'unified_search' => true,
    'comment' => 'First name of the contact',
    'merge_filter' => 'selected',
    'required' => false,
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'size' => '20',
  ),
  'passport_issue_date' =>
  array (
    'required' => true,
    'name' => 'passport_issue_date',
    'vname' => 'LBL_PASSPORT_ISSUE_DATE',
    'type' => 'date',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'size' => '20',
  ),
  'passport_issued' =>
  array (
    'required' => false,
    'name' => 'passport_issued',
    'vname' => 'LBL_PASSPORT_ISSUED',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => '255',
    'size' => '20',
  ),
  'address_temporary' =>
  array (
    'required' => false,
    'name' => 'address_temporary',
    'vname' => 'LBL_ADDRESS_TEMPORARY',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => '255',
    'size' => '20',
  ),
  'address_permanent' =>
  array (
    'required' => false,
    'name' => 'address_permanent',
    'vname' => 'LBL_ADDRESS_PERMANENT',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => '255',
    'size' => '20',
  ),
  'address_actual' =>
  array (
    'required' => true,
    'name' => 'address_actual',
    'vname' => 'LBL_ADDRESS_ACTUAL',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => '255',
    'size' => '20',
  ),
  'addressl_actual' =>
  array (
    'required' => false,
    'name' => 'addressl_actual',
    'vname' => 'LBL_ADDRESSL_ACTUAL',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => '255',
    'size' => '20',
  ),
  'addressl_legal' =>
  array (
    'required' => false,
    'name' => 'addressl_legal',
    'vname' => 'LBL_ADDRESSL_LEGAL',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => '255',
    'size' => '20',
  ),
  'phone' =>
  array (
    'required' => false,
    'name' => 'phone',
    'vname' => 'LBL_PHONE',
    'type' => 'int',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => '11',
    'size' => '20',
    'disable_num_format' => '',
  ),
  'inn_and_kpp' =>
  array (
    'required' => false,
    'name' => 'inn_and_kpp',
    'vname' => 'LBL_INN_AND_KPP',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => '20',
    'size' => '20',
  ),
  'account_and_bank' =>
  array (
    'required' => false,
    'name' => 'account_and_bank',
    'vname' => 'LBL_ACCOUNT_AND_BANK',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => '20',
    'size' => '20',
  ),
  'name_general_director' =>
  array (
    'required' => true,
    'name' => 'name_general_director',
    'vname' => 'LBL_NAME_GENERAL_DIRECTOR',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => '100',
    'size' => '20',
  ),
  'email' =>
  array (
    'required' => false,
    'name' => 'email',
    'vname' => 'LBL_EMAIL',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => '50',
    'size' => '20',
  ),
  'date_entered' =>
  array (
    'name' => 'date_entered',
    'vname' => 'LBL_DATE_ENTERED',
    'type' => 'datetime',
    'group' => 'created_by_name',
    'comment' => 'Date record created',
    'required' => false,
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => '255',
    'size' => '20',
  ),
  'date_modified' =>
  array (
    'name' => 'date_modified',
    'vname' => 'LBL_DATE_MODIFIED',
    'type' => 'datetime',
    'group' => 'modified_by_name',
    'comment' => 'Date record last modified',
    'required' => false,
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => '255',
    'size' => '20',
  ),
  'last_and_middle_name' =>
  array (
    'required' => false,
    'name' => 'last_and_middle_name',
    'vname' => 'LBL_LAST_AND_MIDDLE_NAME',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => '50',
    'size' => '20',
  ),
  'phone_mobile' =>
  array (
    'name' => 'phone_mobile',
    'vname' => 'LBL_PHONE_MOBILE',
    'type' => 'phone',
    'dbType' => 'varchar',
    'len' => '11',
    'unified_search' => true,
    'comment' => 'Mobile phone number of the contact',
    'merge_filter' => 'enabled',
    'required' => false,
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'size' => '20',
    'disable_num_format' => '',
  ),
  'phone_fax' =>
  array (
    'name' => 'phone_fax',
    'vname' => 'LBL_PHONE_FAX',
    'type' => 'varchar',
    'dbType' => 'varchar',
    'len' => '255',
    'unified_search' => true,
    'comment' => 'Contact fax number',
    'merge_filter' => 'enabled',
    'required' => false,
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'size' => '200',
    'disable_num_format' => '',
  ),
  'phone_work' =>
  array (
    'name' => 'phone_work',
    'vname' => 'LBL_PHONE_WORK',
    'type' => 'phone',
    'dbType' => 'varchar',
    'len' => '11',
    'audited' => false,
    'unified_search' => true,
    'comment' => 'Work phone number of the contact',
    'merge_filter' => 'enabled',
    'required' => false,
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'reportable' => true,
    'size' => '20',
    'disable_num_format' => '',
  ),
  'phone_home' =>
  array (
    'name' => 'phone_home',
    'vname' => 'LBL_PHONE_HOME',
    'type' => 'phone',
    'dbType' => 'varchar',
    'len' => '11',
    'unified_search' => true,
    'comment' => 'Home phone number of the contact',
    'merge_filter' => 'enabled',
    'required' => false,
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'size' => '20',
    'disable_num_format' => '',
  ),
  'title' =>
  array (
    'name' => 'title',
    'vname' => 'LBL_TITLE',
    'type' => 'varchar',
    'len' => '100',
    'comment' => 'The title of the contact',
    'required' => false,
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'size' => '20',
  ),
  'passport_first_name' =>
  array (
    'required' => false,
    'name' => 'passport_first_name',
    'vname' => 'LBL_PASSPORT_FIRST_NAME',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => '255',
    'size' => '20',
  ),
  'passport_last_name' =>
  array (
    'required' => false,
    'name' => 'passport_last_name',
    'vname' => 'LBL_PASSPORT_LAST_NAME',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => '255',
    'size' => '20',
  ),
  'passport_middle_name' =>
  array (
    'required' => false,
    'name' => 'passport_middle_name',
    'vname' => 'LBL_PASSPORT_MIDDLE_NAME',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => '255',
    'size' => '20',
  ),
  'prospect_lists' =>
      array (
        'name' => 'prospect_lists',
        'type' => 'link',
        'relationship' => 'prospect_list_sphr_Client',
        'module'=>'ProspectLists',
        'source'=>'non-db',
        'vname'=>'LBL_PROSPECT_LIST',
      ),
    'idn' =>
      array (
        'name' => 'idn',
        'vname' => '№',
        'type' => 'int',
        'comment' => 'Ordinal number record created',
        'required' => false,
        'massupdate' => 0,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'reportable' => true,
        'len' => '11',
        'size' => '20',
        'disable_num_format' => '1',
      ),
),
	'relationships'=>array (
    'prospect_list_sphr_client' => array('lhs_module'=> 'ProspectLists', 'lhs_table'=> 'prospect_lists', 'lhs_key' => 'id',
                 'rhs_module'=> 'sphr_Client', 'rhs_table'=> 'sphr_client', 'rhs_key' => 'id','join_table' =>'prospect_lists_prospects',
                 'join_key_lhs' => 'prospect_list_id', 'join_key_rhs' => 'related_id', 'relationship_role_column' => 'related_type',
                 'relationship_role_column_value' => 'sphr_Client',
                 'relationship_type'=>'many-to-many'),
),
	'optimistic_locking'=>true,
);
if (!class_exists('VardefManager')){
        require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('sphr_Client','sphr_Client', array('basic','assignable','person'));
