<?php
/*********************************************************************************
 * SugarCRM is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2011 SugarCRM Inc.
 * 
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 * 
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 * 
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 * 
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 * 
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo. If the display of the logo is not reasonably feasible for
 * technical reasons, the Appropriate Legal Notices must display the words
 * "Powered by SugarCRM".
 ********************************************************************************/

$relationships = array (
  'sphr_owner_sphr_object' => 
  array (
    'id' => '351df315-84b5-6758-1ea7-4fdadfc46b2f',
    'relationship_name' => 'sphr_owner_sphr_object',
    'lhs_module' => 'sphr_Owner',
    'lhs_table' => 'sphr_owner',
    'lhs_key' => 'id',
    'rhs_module' => 'sphr_Object',
    'rhs_table' => 'sphr_object',
    'rhs_key' => 'id',
    'join_table' => 'sphr_owner_sphr_object_c',
    'join_key_lhs' => 'sphr_owner9f16r_owner_ida',
    'join_key_rhs' => 'sphr_owneredcf_object_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'sphr_object_sphr_interest' => 
  array (
    'id' => '372d5c7a-eb99-3e43-f828-4fdadf45d042',
    'relationship_name' => 'sphr_object_sphr_interest',
    'lhs_module' => 'sphr_Object',
    'lhs_table' => 'sphr_object',
    'lhs_key' => 'id',
    'rhs_module' => 'sphr_Interest',
    'rhs_table' => 'sphr_interest',
    'rhs_key' => 'id',
    'join_table' => 'sphr_objectphr_interest_c',
    'join_key_lhs' => 'sphr_objec2883_object_ida',
    'join_key_rhs' => 'sphr_objec057enterest_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => 'default',
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'sphr_object_sphr_reserve' => 
  array (
    'id' => '3775c923-1cb8-2bd5-e7f7-4fdadfab0996',
    'relationship_name' => 'sphr_object_sphr_reserve',
    'lhs_module' => 'sphr_Object',
    'lhs_table' => 'sphr_object',
    'lhs_key' => 'id',
    'rhs_module' => 'sphr_Reserve',
    'rhs_table' => 'sphr_reserve',
    'rhs_key' => 'id',
    'join_table' => 'sphr_objectsphr_reserve_c',
    'join_key_lhs' => 'sphr_objec6f3b_object_ida',
    'join_key_rhs' => 'sphr_objec1157reserve_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'sphr_object_opportunities' => 
  array (
    'id' => '37bc81b1-18ae-7b30-fcb8-4fdadf6fb31d',
    'relationship_name' => 'sphr_object_opportunities',
    'lhs_module' => 'sphr_Object',
    'lhs_table' => 'sphr_object',
    'lhs_key' => 'id',
    'rhs_module' => 'Opportunities',
    'rhs_table' => 'opportunities',
    'rhs_key' => 'id',
    'join_table' => 'sphr_objectpportunities_c',
    'join_key_lhs' => 'sphr_objec388d_object_ida',
    'join_key_rhs' => 'sphr_objecbc4aunities_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => 'default',
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'cosib_queries_sphr_object' => 
  array (
    'id' => '39c7f3fb-b977-f2af-6d87-4fdadf20dd3b',
    'relationship_name' => 'cosib_queries_sphr_object',
    'lhs_module' => 'cosib_queries',
    'lhs_table' => 'cosib_queries',
    'lhs_key' => 'id',
    'rhs_module' => 'sphr_Object',
    'rhs_table' => 'sphr_object',
    'rhs_key' => 'id',
    'join_table' => 'cosib_queri_sphr_object_c',
    'join_key_lhs' => 'cosib_quer91b5queries_ida',
    'join_key_rhs' => 'cosib_quer4238_object_idb',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => 'default',
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'accounts_sphr_object' => 
  array (
    'id' => '3a4da5e6-33b7-9de8-fbd1-4fdadff42726',
    'relationship_name' => 'accounts_sphr_object',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'sphr_Object',
    'rhs_table' => 'sphr_object',
    'rhs_key' => 'id',
    'join_table' => 'accounts_sphr_object_c',
    'join_key_lhs' => 'accounts_sfb36ccounts_ida',
    'join_key_rhs' => 'accounts_s40ad_object_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'sphr_developer_sphr_object' => 
  array (
    'id' => '3b222109-87d0-13a5-15ca-4fdadf217fb4',
    'relationship_name' => 'sphr_developer_sphr_object',
    'lhs_module' => 'sphr_Developer',
    'lhs_table' => 'sphr_developer',
    'lhs_key' => 'id',
    'rhs_module' => 'sphr_Object',
    'rhs_table' => 'sphr_object',
    'rhs_key' => 'id',
    'join_table' => 'sphr_develo_sphr_object_c',
    'join_key_lhs' => 'sphr_devel6664veloper_ida',
    'join_key_rhs' => 'sphr_devel402f_object_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'sphr_object_notes' => 
  array (
    'id' => '3beece53-097a-378d-a874-4fdadf194465',
    'relationship_name' => 'sphr_object_notes',
    'lhs_module' => 'sphr_Object',
    'lhs_table' => 'sphr_object',
    'lhs_key' => 'id',
    'rhs_module' => 'Notes',
    'rhs_table' => 'notes',
    'rhs_key' => 'id',
    'join_table' => 'sphr_object_notes_c',
    'join_key_lhs' => 'sphr_objec205c_object_ida',
    'join_key_rhs' => 'sphr_objec37a9esnotes_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'sphr_intermediary_sphr_object' => 
  array (
    'id' => '3c317e28-5d25-8829-ab96-4fdadf0e5693',
    'relationship_name' => 'sphr_intermediary_sphr_object',
    'lhs_module' => 'sphr_Intermediary',
    'lhs_table' => 'sphr_intermediary',
    'lhs_key' => 'id',
    'rhs_module' => 'sphr_Object',
    'rhs_table' => 'sphr_object',
    'rhs_key' => 'id',
    'join_table' => 'sphr_interm_sphr_object_c',
    'join_key_lhs' => 'sphr_intera323mediary_ida',
    'join_key_rhs' => 'sphr_inter665b_object_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'sphr_object_documents' => 
  array (
    'id' => '3eef2bf7-92d4-77b1-fa81-4fdadfad0ae0',
    'relationship_name' => 'sphr_object_documents',
    'lhs_module' => 'sphr_Object',
    'lhs_table' => 'sphr_object',
    'lhs_key' => 'id',
    'rhs_module' => 'Documents',
    'rhs_table' => 'documents',
    'rhs_key' => 'id',
    'join_table' => 'sphr_object_documents_c',
    'join_key_lhs' => 'sphr_objec1b6c_object_ida',
    'join_key_rhs' => 'sphr_objec92efcuments_idb',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => 'default',
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'sphr_object_sphr_show_object' => 
  array (
    'id' => '3fbc0601-3ae3-884b-a7b9-4fdadf6f1eef',
    'relationship_name' => 'sphr_object_sphr_show_object',
    'lhs_module' => 'sphr_Object',
    'lhs_table' => 'sphr_object',
    'lhs_key' => 'id',
    'rhs_module' => 'sphr_Show_object',
    'rhs_table' => 'sphr_show_object',
    'rhs_key' => 'id',
    'join_table' => 'sphr_object_show_object_c',
    'join_key_lhs' => 'sphr_objecdf1f_object_ida',
    'join_key_rhs' => 'sphr_objec4a69_object_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'sphr_client_sphr_object' => 
  array (
    'id' => '41322785-9181-94d3-c1ff-4fdadf4018c4',
    'relationship_name' => 'sphr_client_sphr_object',
    'lhs_module' => 'sphr_Client',
    'lhs_table' => 'sphr_client',
    'lhs_key' => 'id',
    'rhs_module' => 'sphr_Object',
    'rhs_table' => 'sphr_object',
    'rhs_key' => 'id',
    'join_table' => 'sphr_client_sphr_object_c',
    'join_key_lhs' => 'sphr_clien88c3_client_ida',
    'join_key_rhs' => 'sphr_clien826b_object_idb',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => 'default',
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'sphr_object_cosib_messages' => 
  array (
    'rhs_label' => 'Сообщения',
    'lhs_label' => 'Объекты',
    'rhs_subpanel' => 'default',
    'lhs_module' => 'sphr_Object',
    'rhs_module' => 'cosib_messages',
    'relationship_type' => 'one-to-many',
    'readonly' => true,
    'deleted' => false,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
    'relationship_name' => 'sphr_object_cosib_messages',
  ),
);
?>
