<?PHP
/*********************************************************************************
 * SugarCRM is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2011 SugarCRM Inc.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo. If the display of the logo is not reasonably feasible for
 * technical reasons, the Appropriate Legal Notices must display the words
 * "Powered by SugarCRM".
 ********************************************************************************/

/**
 * THIS CLASS IS GENERATED BY MODULE BUILDER
 * PLEASE DO NOT CHANGE THIS CLASS
 * PLACE ANY CUSTOMIZATIONS IN Cosib_client_trips
 */


class Cosib_client_trips_sugar extends Basic {
	var $new_schema = true;
	var $module_dir = 'Cosib_client_trips';
	var $object_name = 'Cosib_client_trips';
	var $table_name = 'cosib_client_trips';
	var $importable = true;
	var $disable_row_level_security = true ; // to ensure that modules created and deployed under CE will continue to function under team security if the instance is upgraded to PRO
		var $id;
		var $name;
		var $date_entered;
		var $date_modified;
		var $modified_user_id;
		var $modified_by_name;
		var $created_by;
		var $created_by_name;
		var $description;
		var $deleted;
		var $created_by_link;
		var $modified_user_link;
		var $assigned_user_id;
		var $assigned_user_name;
		var $assigned_user_link;
		var $residence;
		var $arrival;
		var $trip_place;
		var $date_departure;
		var $date_arrive;
		var $status;
		function Cosib_client_trips_sugar(){
		parent::Basic();
	}

	function bean_implements($interface){
		switch($interface){
			case 'ACL': return true;
		}
		return false;
	}
	//for calendar
    function load_list_calendar($from='',$to=''){
    	$query = $this->create_list_calendar($from,$to);
    	$result = $this->db->query($query);
    	$list = array();
        while($rec = $this->db->fetchByAssoc($result)){
          $rec['object_list'] = $this->load_list_object_calendar($rec['id']);
          $list[]= $rec;
        }
        return $list;
    }
    function create_list_calendar($from='',$to=''){
    	$where = ($from!='')?' date_arrive >= \''.$this->db->quote(trim($from)).'\' ':'';
        $where .= ($to!='')?(($where!='')?' AND ':'').' date_arrive <= \''.$this->db->quote(trim($_REQUEST['to'])).'\' ':'';
        $query = "SELECT cct.id,cct.status, cct.date_arrive, date_departure,   CONCAT(IFNULL(jt3.first_name,''),' ',IFNULL(jt3.last_name,'')) assigned_user_name, CONCAT(IFNULL(sc.first_name,''),' ',IFNULL(sc.last_name,'')) client_name  FROM `cosib_client_trips`  cct   LEFT JOIN  `users` jt3 ON
					jt3.id= cct.assigned_user_id AND jt3.deleted=0
 					AND jt3.deleted=0 LEFT JOIN `cosib_clien_sphr_client_c` ccsc ON ccsc.cosib_cliea115t_trips_idb=cct.id AND ccsc.deleted=0 LEFT JOIN `sphr_client` sc ON sc.id =ccsc.cosib_cliee6e0_client_ida  AND sc.deleted =0
				  WHERE ".$where.(($where!='')?' AND ':'')."  cct.deleted=0 ORDER BY cct.date_entered DESC";

		return $query;

    }
    function load_list_object_calendar($id){
           $query = "SELECT so.id,so.name   FROM `sphr_object`  so
					  LEFT JOIN `cosib_clien_sphr_object_c` ccso ON ccso.cosib_clief5bd_object_idb=so.id  AND ccso.deleted=0
					  WHERE    ccso.cosib_clie09c9t_trips_ida='$id' AND so.deleted=0  ORDER BY ccso.date_modified DESC";

		  $result=$this->db->query($query);
		  $list=array();
		  while($rec =  $this->db->fetchByAssoc($result)){
		    $list[]= $rec;
		  }
          return $list;
    }

}
?>