<?php
if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');
/*********************************************************************************
 * SugarCRM is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004 - 2010 SugarCRM Inc.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo. If the display of the logo is not reasonably feasible for
 * technical reasons, the Appropriate Legal Notices must display the words
 * "Powered by SugarCRM".
 ********************************************************************************/


  /*********************************************************************************
  *
  * File generated by the RAPIRA Translation Suite ----------
  *
  ***********************************************************************likhobory*/

  /*********************************************************************************
  * Description : Defines the Russian language pack for the base application.
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s):
  *********************************************************************************/

$mod_strings = array (

'LBL_BLANK'	=> ' ',

'LBL_MODULE_NAME' => 'Звонки' ,
'LBL_MODULE_TITLE' => 'Звонки - ГЛАВНАЯ' ,
'LBL_SEARCH_FORM_TITLE' => 'Поиск звонка' ,
'LBL_LIST_FORM_TITLE' => 'Список звонков' ,
'LBL_NEW_FORM_TITLE' => 'Назначить мероприятие' ,
'LBL_LIST_CLOSE' => 'Закрыть' ,
'LBL_LIST_SUBJECT' => 'Тема' ,
'LBL_LIST_CONTACT' => 'Контакт' ,
'LBL_LIST_RELATED_TO' => 'Относится к' ,
'LBL_LIST_RELATED_TO_ID' => 'Относится к ID',
'LBL_LIST_DATE' => 'Дата' ,
'LBL_LIST_TIME' => 'Время' ,
'LBL_LIST_DURATION' => 'Продолжительность' ,
'LBL_LIST_DIRECTION' => 'Направление' ,
'LBL_SUBJECT' => 'Тема:' ,
'LBL_REMINDER' => 'Напоминание:' ,
'LBL_CONTACT_NAME' => 'Контакт:' ,
'LBL_DESCRIPTION_INFORMATION' => 'Описание' ,
'LBL_DESCRIPTION' => 'Описание:' ,
'LBL_STATUS' => 'Статус:' ,
'LBL_DIRECTION' => 'Направление:' ,
'LBL_DATE' => 'Дата:' ,
'LBL_DURATION' => 'Продолжительность:' ,
'LBL_DURATION_HOURS' => 'Продолжительность (час.):' ,
'LBL_DURATION_MINUTES' => 'Продолжительность (мин.):' ,
'LBL_HOURS_MINUTES' => '(часов:минут)' ,
'LBL_CALL' => 'Звонок:' ,
'LBL_DATE_TIME' => 'Дата и время:' ,
'LBL_TIME' => 'Время:' ,
'LBL_HOURS_ABBREV' => 'час.' ,
'LBL_MINSS_ABBREV' => 'мин.' ,
'LBL_COLON' => ':' ,
'LBL_DEFAULT_STATUS' => 'Запланировано' ,
'LNK_NEW_CALL' => 'Назначить звонок' ,
'LNK_NEW_MEETING' => 'Назначить встречу' ,

'LNK_CALL_LIST' => 'Звонки' ,

'LNK_IMPORT_CALLS' => 'Импорт звонков',
'ERR_DELETE_RECORD' => 'Перед удалением должен быть указан номер записи.' ,
'NTC_REMOVE_INVITEE' => 'Вы уверены, что хотите удалить это приглашенное лицо из данного звонка?' ,
'LBL_INVITEE' => 'Приглашенные' ,
'LBL_RELATED_TO' => 'Относится к:' ,
'LNK_NEW_APPOINTMENT' => 'Назначить встречу/звонок' ,
'LBL_SCHEDULING_FORM_TITLE' => 'Планирование' ,
'LBL_ADD_INVITEE' => 'Добавить приглашённых' ,
'LBL_NAME' => 'Имя' ,
'LBL_FIRST_NAME' => 'Имя' ,
'LBL_LAST_NAME' => 'Фамилия' ,
'LBL_EMAIL' => 'E-mail' ,
'LBL_PHONE' => 'Тел.' ,
'LBL_REMINDER' => 'Напоминание:' ,
'LBL_SEND_BUTTON_TITLE' => 'Отправить приглашение [Alt+I]' ,
'LBL_SEND_BUTTON_KEY' => 'I' ,
'LBL_SEND_BUTTON_LABEL' => 'Отсылка приглашений' ,
'LBL_DATE_END' => 'Дата окончания' ,
'LBL_TIME_END' => 'Время окончания' ,
'LBL_REMINDER_TIME' => 'Время напоминания' ,
'LBL_SEARCH_BUTTON' => 'Найти' ,
'LBL_ACTIVITIES_REPORTS' => 'Отчеты по мероприятиям',  
'LBL_ADD_BUTTON' => 'Добавить' ,
'LBL_DEFAULT_SUBPANEL_TITLE' => 'Звонки' ,
'LBL_LOG_CALL' => 'Журнал звонков' ,
'LNK_SELECT_ACCOUNT' => 'Выбор контрагента' ,
'LNK_NEW_ACCOUNT' => 'Новый контрагент' ,
'LNK_NEW_OPPORTUNITY' => 'Новая сделка' ,
'LBL_DEL' => 'Удалить' ,
'LBL_LEADS_SUBPANEL_TITLE' => 'Предварительные контакты',
'LBL_CONTACTS_SUBPANEL_TITLE' => 'Контакты' ,
'LBL_USERS_SUBPANEL_TITLE' => 'Пользователи' ,
'LBL_OUTLOOK_ID' => 'ID Outlook' ,
'LBL_MEMBER_OF' => 'Состоит в' ,
'LBL_HISTORY_SUBPANEL_TITLE' => 'Заметки'  ,
'LBL_LIST_ASSIGNED_TO_NAME' => 'Ответственный(ая)',
'LBL_LIST_MY_CALLS' => 'Мои звонки',
'LBL_SELECT_FROM_DROPDOWN' => 'Прежде всего выберите значение из списка "Относится к".',
'LBL_ASSIGNED_TO_NAME' => 'Ответственный(ая)',
'LBL_ASSIGNED_TO_ID' => 'Ответственный(ID)',
'NOTICE_DURATION_TIME' => 'Продолжительность разговора должна быть больше 0 минут',
'LBL_CALL_INFORMATION' => 'Описание звонка',
'LBL_REMOVE' => 'удал.',
);

?>