<?php
if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');
/*********************************************************************************
 * SugarCRM is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004 - 2010 SugarCRM Inc.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo. If the display of the logo is not reasonably feasible for
 * technical reasons, the Appropriate Legal Notices must display the words
 * "Powered by SugarCRM".
 ********************************************************************************/
 
 /*********************************************************************************
  *
  * File generated by the RAPIRA Translation Suite ----------
  *
  ***********************************************************************likhobory*/

  /*********************************************************************************
  * Description : Defines the Russian language pack for the base application.
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s):
  *********************************************************************************/

$mod_strings = array (
'ERR_DELETE_RECORD' => 'Для удаления встречи должен быть определен номер записи.' ,
	
'LBL_ACCEPT_THIS' =>'Принять?',
'LBL_ADD_BUTTON' => 'Добавить' ,
'LBL_ADD_INVITEE' => 'Добавить приглашённых' ,

'LBL_COLON' => ':' ,
'LBL_CONTACT_NAME' => 'Контакт:' ,
'LBL_CONTACTS_SUBPANEL_TITLE' => 'Контакты' ,
'LBL_CREATED_BY' => 'Кем создано' ,
'LBL_DATE_END' => 'Дата окончания' ,
'LBL_DATE_TIME' => 'Дата и время начала:' ,
'LBL_DATE' => 'Дата начала:' ,
'LBL_DEFAULT_STATUS' => 'Запланирована' ,
'LBL_DEFAULT_SUBPANEL_TITLE' => 'Встречи' ,
'LBL_DEL' => 'Удалить' ,
'LBL_DESCRIPTION_INFORMATION' => 'Описание' ,
'LBL_DESCRIPTION' => 'Описание:' ,
'LBL_DURATION_HOURS' => 'Продолжительность (час.):' ,
'LBL_DURATION_MINUTES' => 'Продолжительность (мин.):' ,
'LBL_DURATION' => 'Продолжительность:' ,
'LBL_EMAIL' => 'E-mail' ,
'LBL_FIRST_NAME' => 'Имя' ,
'LBL_HISTORY_SUBPANEL_TITLE' => 'Заметки' ,
'LBL_HOURS_ABBREV' => 'час.' ,
'LBL_HOURS_MINS' => '(часов:минут)' ,
'LBL_INVITEE' => 'Приглашенные' ,
'LBL_LAST_NAME' => 'Фамилия' ,
'LBL_ASSIGNED_TO_NAME'=>'Ответственный(ая):',
'LBL_LIST_ASSIGNED_TO_NAME' => 'Ответственный(ая)',
'LBL_LIST_CLOSE' => 'Закрыть' ,
'LBL_LIST_CONTACT' => 'Контакт' ,
'LBL_LIST_DATE_MODIFIED' => 'Дата изменения' ,
'LBL_LIST_DATE' => 'Дата начала' ,
'LBL_LIST_DIRECTION' => 'Направление',
'LBL_LIST_DUE_DATE' => 'Дата завершения' ,
'LBL_LIST_FORM_TITLE' => 'Список встреч' ,
'LBL_LIST_MY_MEETINGS' => 'Мои встречи',
'LBL_LIST_RELATED_TO' => 'Относится к' ,
'LBL_LIST_STATUS' => 'Статус' ,
'LBL_LIST_SUBJECT' => 'Тема' ,
'LBL_LIST_TIME' => 'Время начала' ,
'LBL_LEADS_SUBPANEL_TITLE' => 'Предварительные контакты',
'LBL_LOCATION' => 'Место:' ,
'LBL_MEETING' => 'Встреча:' ,
'LBL_MINSS_ABBREV' => 'мин.' ,
'LBL_MODIFIED_BY' => 'Кем исправлено' ,
'LBL_MODULE_NAME' => 'Встречи' ,
'LBL_MODULE_TITLE' => 'Встречи - ГЛАВНАЯ' ,
'LBL_NAME' => 'Имя' ,
'LBL_NEW_FORM_TITLE' => 'Назначить встречу' ,
'LBL_OUTLOOK_ID' => 'ID Outlook' ,
'LBL_PHONE' => 'Тел. (раб. :' ,
'LBL_REMINDER_TIME' => 'Время напоминания' ,
'LBL_REMINDER' => 'Напоминание:' ,
'LBL_REMOVE' => 'удал.',
'LBL_SCHEDULING_FORM_TITLE' => 'Планирование' ,
'LBL_SEARCH_BUTTON' => 'Найти' ,
'LBL_SEARCH_FORM_TITLE' => 'Поиск встречи' ,
'LBL_SEND_BUTTON_KEY' => 'I' ,
'LBL_SEND_BUTTON_LABEL' => 'Отправить приглашения' ,
'LBL_SEND_BUTTON_TITLE' => 'Отправить приглашение [Alt+I]' ,
'LBL_STATUS' => 'Статус:' ,
'LBL_SUBJECT' => 'Тема:' ,
'LBL_TIME' => 'Время начала:' ,
'LBL_USERS_SUBPANEL_TITLE' => 'Пользователи' ,
'LBL_ACTIVITIES_REPORTS' => 'Отчеты по мероприятиям',   
	

'LNK_MEETING_LIST' => 'Встречи' ,
'LNK_NEW_APPOINTMENT' => 'Назначить встречу/звонок' ,

'LNK_NEW_MEETING' => 'Назначить встречу' ,
'LNK_IMPORT_MEETINGS' => 'Импорт встреч',

'NTC_REMOVE_INVITEE' => 'Вы уверены, что хотите удалить это приглашение из данной встречи?' ,
'LBL_CREATED_USER' => 'Создано',
'LBL_MODIFIED_USER' => 'Изменено',
'NOTICE_DURATION_TIME' => 'Продолжительность встречи должна быть больше 0 минут',
'LBL_MEETING_INFORMATION' => 'Описание встречи',
);
?> 	