<?php
if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');
/*********************************************************************************
 * SugarCRM is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004 - 2010 SugarCRM Inc.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo. If the display of the logo is not reasonably feasible for
 * technical reasons, the Appropriate Legal Notices must display the words
 * "Powered by SugarCRM".
 ********************************************************************************/

  /*********************************************************************************
  *
  * File generated by the RAPIRA Translation Suite  ----------
  *
  ***********************************************************************likhobory*/

  /*********************************************************************************
  * Description : Defines the Russian language pack for the base application.
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s):
  *********************************************************************************/

$mod_strings = array (

    'LBL_SYSOPTS_1'                     => 'Установите параметры конфигурации.',
    'LBL_SYSOPTS_2'                     => 'Какой тип базы данных будет использоваться в системе?',
    'LBL_SYSOPTS_CONFIG'                => 'Конфигурация системы',
    'LBL_SYSOPTS_DB_TYPE'               => 'Доступные типы баз данных',
    'LBL_SYSOPTS_DB'                    => 'Укажите тип базы данных',
    'LBL_SYSOPTS_DB_TITLE'              => 'Тип базы данных',
    'LBL_SYSOPTS_ERRS_TITLE'            => 'Пожалуйста, исправьте следующие ошибки перед тем как продолжить:',
	'LBL_MAKE_DIRECTORY_WRITABLE'       => 'Следующие папки должны быть доступны для записи:',





    'DEFAULT_CHARSET'                   => 'UTF-8' ,
    'ERR_ADMIN_USER_NAME_BLANK'         => 'Укажите имя администратора системы',
    'ERR_ADMIN_PASS_BLANK'              => 'Укажите пароль администратора системы' ,

    //'ERR_CHECKSYS_CALL_TIME'          => 'Call Time Pass включен (выключить эту опцию можно в php.ini)',
    'ERR_CHECKSYS'                      => 'В процессе проверки совместимости были обнаружены ошибки. Для того, чтобы ваша система функционировала правильно, пожалуйста, выполните необходимые действия над пунктами, указанными ниже и повторите проверку или начните установку заново.',
    'ERR_CHECKSYS_CALL_TIME'            => 'Allow Call Time Pass Reference выключена (включите эту опцию в php.ini)',
    'ERR_CHECKSYS_CURL'                 => 'Не найдено: планировщик будет работать с ограниченной	функциональностью' ,
    'ERR_CHECKSYS_FASTCGI_LOGGING'      => 'Для оптимального использования IIS / FastCGI SAPI, установите параметр fastcgi.logging в файле php.ini равным 0.',
	'ERR_CHECKSYS_IMAP'                 => 'Не найдено: для нормальной работы входящей почты и кампаний необходимо наличие IMAP-библиотек' ,
    'ERR_CHECKSYS_MSSQL_MQGPC'          => 'Magic Quotes GPC нельзя включить при использовании MS SQL Server' ,
    'ERR_CHECKSYS_MEM_LIMIT_0'          => 'Предупреждение:  ',
    'ERR_CHECKSYS_MEM_LIMIT_1'          => '(Установите это значение в ' ,
    'ERR_CHECKSYS_MEM_LIMIT_2'          => 'M или более в php.ini)' ,
    'ERR_CHECKSYS_MYSQL_VERSION'        => 'Минимальная версия 4.1.2 - Найдена: ' ,
    'ERR_CHECKSYS_NO_SESSIONS'          => 'Ошибка при чтении и записи сессионных переменных. Продолжение установки невозможно.' ,
    'ERR_CHECKSYS_NOT_VALID_DIR'        => 'Неверная папка' ,
    'ERR_CHECKSYS_NOT_WRITABLE'         => 'Предупреждение: установлена защита от записи' ,
    'ERR_CHECKSYS_PHP_INVALID_VER'      => 'Неверная версия PHP. Установлена версия: (' ,
    'ERR_CHECKSYS_IIS_INVALID_VER'      => 'Ваша версия IIS не поддерживается.  Вам необходимо установить версию, совместимую с текущей версией Sugar.  Обратитесь к разделу <b>Compatibility Matrix</b>, находящемуся в примечаниях к релизу, чтобы уточнить номер поддерживаемой версии IIS. Номер текущей версии: ',
	'ERR_CHECKSYS_FASTCGI'              => 'Модуль FastCGI для исполнения PHP не установлен. Вам необходимо установить и настроить версию FastCGI, совместимую с текущей версией Sugar. Обратитесь к разделу <b>Compatibility Matrix</b>, находящемуся в примечаниях к релизу, чтобы уточнить номер поддерживаемой версии FastCGI. Подробную информацию вы можете получить здесь: <a href="http://www.iis.net/php/" target="_blank">http://www.iis.net/php/</a> ',
	'ERR_CHECKSYS_FASTCGI_LOGGING'      => 'Для оптимального использования IIS / FastCGI SAPI, установите параметр fastcgi.logging в файле php.ini равным 0.',
	'ERR_CHECKSYS_PHP_UNSUPPORTED'      => 'Установлена неподдерживаемая версия PHP <br>( ' ,
    'LBL_DB_UNAVAILABLE'                => 'База данных недоступна',
    'LBL_CHECKSYS_DB_SUPPORT_NOT_AVAILABLE' => 'Поддержка базы данных не обнаружена. Убедитесь, что у вас есть необходимые драйвера для одного из следующих типов БДD: MySQL, MS SQLServer или Oracle. Вероятно, вам необходимо раскомментировать соответствующее расширение в файле php.ini, или перекомпилировать бинарный файл в соответствии с вашей версией PHP. Пожалуйста, обратитесь к руководству пользователя PHP за более подробной информацией о поддержке вашего типа БД.',
    'LBL_CHECKSYS_XML_NOT_AVAILABLE'        => 'Функции для работы с XML-парсером не обнаружены. Вероятно, вам необходимо раскомментировать соответствующее расширение в файле php.ini, или перекомпилировать бинарный файл в соответствии с вашей версией PHP. Пожалуйста, обратитесь к руководству пользователя PHP за более подробной информацией.',
    'ERR_CHECKSYS_MBSTRING'             => 'Не найдена функция, связанная с расширением MBSTRING. <br/><br/>Вероятно, модуль MBSTRING не включен по умолчанию в PHP и должен быть активирован путем добавления опции --enable-mbstring при сборке PHP. Пожалуйста, обратитесь к руководству пользователя PHP за более подробной информацией.',
    'ERR_CHECKSYS_SESSION_SAVE_PATH_NOT_SET'       => 'Параметр session.save_path в файле php.ini не установлен или он ссылается на несуществующую папку. Вам необходимо установить данный параметр или убедиться в существовании указанной папки.',
    'ERR_CHECKSYS_SESSION_SAVE_PATH_NOT_WRITABLE'  => 'Параметр session.save_path в файле php.ini ссылается на папку, которая не доступна для записи. Пожалуйста, выполните необходимые шаги для того, чтобы сделать файл доступным для записи. В зависимости от типа вашей операционной системы вам потребуется либо сменить права доступа к файлу, путем выполнения команды "chmod 766", либо, нажав на файле правой кнопкой мыши, получить доступ к свойствам файла и снять отметку с опции "read only".',
    'ERR_CHECKSYS_CONFIG_NOT_WRITABLE'  => 'Файл конфигурации существует, но он не доступен для записи. Пожалуйста, выполните необходимые шаги для того, чтобы сделать файл доступным для записи. В зависимости от типа вашей операционной системы вам потребуется либо сменить права доступа к файлу, путем выполнения команды "chmod 766", либо, нажав на файле правой кнопкой мыши, получить доступ к свойствам файла и снять отметку с опции "read only".',
    'ERR_CHECKSYS_CUSTOM_NOT_WRITABLE'  => 'Указанная папка существует, но она не доступна для записи.  Пожалуйста, выполните необходимые шаги для того, чтобы сделать папку доступной для записи. В зависимости от типа вашей операционной системы вам потребуется либо сменить права доступа к папке, путем выполнения команды "chmod 766", либо, нажав на папке правой кнопкой мыши, получить доступ к её свойствам и снять отметку с опции "read only".',
    'ERR_CHECKSYS_FILES_NOT_WRITABLE'   => 'Перечисленные файлы и папки не доступны для записи или отсутствуют и не могут быть созданы. В зависимости от типа вашей операционной системы для исправления ситуации вам потребуется либо сменить права доступа к файлу или родительской папке путем выполнения команды "chmod 766", либо, нажав на папке правой кнопкой мыши, получить доступ к свойствам папки и снять отметку с опции  "read only", применив данное действие ко всем подпапкам.',
    //'ERR_CHECKSYS_SAFE_MODE'          => 'Безопасный режим включен(выключить эту опцию можно в php.ini)' ,
    'ERR_CHECKSYS_SAFE_MODE'            => 'Безопасный режим включен(выключить эту опцию можно в php.ini)' ,
    'ERR_CHECKSYS_ZLIB'                 => 'Не найдено: модуль zlib, позволяющий повысить производительность системы при использовании zlib-сжатия' ,
    'ERR_DB_ADMIN'                      => 'Неверный логин или пароль администратора БД (Ошибка  ' ,
    'ERR_DB_ADMIN_MSSQL'                => 'Имя администратора базы данных и/или пароль указаны неверно. Невозможно соединиться с сервером: ',
    'ERR_DB_EXISTS_NOT'                 => 'Указанная база данных не существует' ,
    'ERR_DB_EXISTS_WITH_CONFIG'         => 'База данных уже существует. Чтобы установить систему с выбранной базой данных, перезапустите процесс установки и выберите параметр "Удалить и создать заново существующие таблицы SugarCRM?". Для обновления системы используйте Мастер Обновлений в панели администратора. Более детальную информацию о процессе обновления Вы можете получить <a href="http://www.sugarforge.org/content/downloads/" target="_new">здесь</a>.' ,
    'ERR_DB_EXISTS'                     => 'База данных с таким именем уже существует, нельзя создать еще одну базу с таким же именем.' ,
    'ERR_DB_EXISTS_PROCEED'             => 'База данных с подобным именем уже существует. --<br>Вы можете нажать на кнопку "Назад" и указать другое имя базы данных, или же вы можете нажать на кнопку "Далее" и продолжить установку, но в этом случае <strong> все таблицы в этой базе данных будут удалены.</strong>',
    'ERR_DB_HOSTNAME'                   => 'Имя хоста не может быть пустым' ,
    'ERR_DB_INVALID'                    => 'Выбран неверный тип базы данных' ,
    'ERR_DB_LOGIN_FAILURE_MYSQL'        => 'Указанные сервер БД, логин и/или пароль пользователя БД неверны. Соединение не может быть установлено. Укажите правильные данные.' ,
    'ERR_DB_MYSQL_VERSION1'             => 'Версия MySQL ' ,
    'ERR_DB_MYSQL_VERSION2'             => ' не поддерживается. Поддерживаются только MySQL 4.1.х и выше.' ,
    'ERR_DB_NAME'                       => 'Название базы данных не может быть пустым.' ,
    'ERR_DB_NAME2'                      => 'Имя БД не может содержать прямой или обратный слеш, а так же точку.' ,
    'ERR_DB_MSSQL_DB_NAME_INVALID'      => "Имя БД не может содержать следующие символы: '\"', \"'\", '*', '/', '\', '?', ':', '<', '>', '-'",
	'ERR_DB_PASSWORD'                   => 'Пароли для SugarCRM не совпадают.' ,
    'ERR_DB_PRIV_USER'                  => 'Необходим логин администратора.' ,
    'ERR_DB_USER_EXISTS'                => 'Пользователь с указанным именем уже существует. Нельзя создать еще одного пользователя с таким же именем.' ,
    'ERR_DB_USER'                       => 'Имя пользователя SuagrCRM не может быть пустым.' ,
    'ERR_DBCONF_VALIDATION'             => 'Пожалуйста, исправьте следующие ошибки:' ,
    'ERR_DBCONF_PASSWORD_MISMATCH'      => 'Пароли пользователя базы данных Sugar не совпадают.',
    'ERR_ERROR_GENERAL'                 => 'Были обнаружены следующие ошибки:' ,
    'ERR_LANG_CANNOT_DELETE_FILE'       => 'Невозможно удалить файл: ' ,
    'ERR_LANG_MISSING_FILE'             => 'Невозможно найти файл: ' ,
    'ERR_LANG_NO_LANG_FILE'             => 'Не найден языковой файл в include/language: ' ,
    'ERR_LANG_UPLOAD_1'                 => 'Загрузка не удалась. Пожалуйста, попробуйте еще раз.' ,
    'ERR_LANG_UPLOAD_2'                 => 'Языковой пакет должны быть ZIP-архивом.' ,
    'ERR_LANG_UPLOAD_3'                 => 'PHP не может переместить временный файл в папку обновления' ,
    'ERR_LICENSE_MISSING'               => 'Пропущены обязательные поля' ,
    'ERR_LICENSE_NOT_FOUND'             => 'Файл лицензии не найден.' ,
    'ERR_LOG_DIRECTORY_NOT_EXISTS'      => 'Указана неверная папка для журналов.' ,
    'ERR_LOG_DIRECTORY_NOT_WRITABLE'    => 'Указанная папка для журналов недоступна для записи.' ,
    'ERR_LOG_DIRECTORY_REQUIRED'        => 'Если вы решили указать собственную папку для журналов - укажите ее расположение' ,
    'ERR_NO_DIRECT_SCRIPT'              => 'Не удалось обработать скрипт.' ,
    'ERR_NO_SINGLE_QUOTE'               => 'Нельзя использовать одинарную кавычку для ' ,
    'ERR_PASSWORD_MISMATCH'             => 'Пароли администратора для SugarCRM не совпадают.' ,
    'ERR_PERFORM_CONFIG_PHP_1'          => 'Невозможно записать в файл<span class=stop>config.php</span>.' ,
    'ERR_PERFORM_CONFIG_PHP_2'          => 'Вы можете продолжить установку, создав файл config.php вручную и скопировав туда нижеследующий текст. Но обязательно убедитесь, что Вы это сделали до перехода к следующему шагу.' ,
    'ERR_PERFORM_CONFIG_PHP_3'          => 'Вы не забыли создать файл config.php?' ,
    'ERR_PERFORM_CONFIG_PHP_4'          => 'Предупреждение: невозможно произвести запись в файл config.php. Пожалуйста, убедитесь, что файл существует.' ,
    'ERR_PERFORM_HTACCESS_1'            => 'Не могу записать в  ' ,
    'ERR_PERFORM_HTACCESS_2'            => ' файл.' ,
    'ERR_PERFORM_HTACCESS_3'            => 'Если Вы хотите защитить ваш файл журнала от чтения его браузером, создайте файл .htaccess со следующей строкой:' ,
    'ERR_PERFORM_NO_TCPIP'              => 'Невозможно подключиться к интернету. Когда соединение будет доступно, пожалуйста, зарегистрируйтесь по адресу: <a href="http://www.sugarcrm.com/crm/products/offline-product-registration.html">http://www.sugarcrm.com/crm/products/offline-product-registration.html</a>.' ,
    'ERR_SESSION_DIRECTORY_NOT_EXISTS'  => 'Указана неверная папка для файлов сессий.' ,
    'ERR_SESSION_DIRECTORY'             => 'Указанная папка сессий недоступна для записи.' ,
    'ERR_SESSION_PATH'                  => 'Если вы решили указать собственную папку для файлов сессий - укажите ее расположение' ,
    'ERR_SI_NO_CONFIG'                  => 'Вы не поместили файл config_si.php в корневую папку или же вы не определили переменную $sugar_config_si в файле config.php' ,
    'ERR_SITE_GUID'                     => 'Если вы решили указать собственный код приложения - укажите его' ,
    'ERR_UPLOAD_MAX_FILESIZE'           => 'Предупреждение: конфигурация PHP должна быть изменена, чтобы разрешить загрузку файлов размером более 6 МБ.' ,
    'LBL_UPLOAD_MAX_FILESIZE_TITLE'     => 'Максимальный размер загружаемого файла',
    'ERR_URL_BLANK'                     => 'URL не может быть пустым.' ,
    'ERR_UW_NO_UPDATE_RECORD'           => 'Невозможно определить расположение' ,
    'ERROR_FLAVOR_INCOMPATIBLE'         => 'Загруженный файл не совместим с установленной версией Sugar Suite: ' ,
    'ERROR_LICENSE_EXPIRED'             => 'Ошибка: Срок действия вашей лицензии истек' ,
    'ERROR_LICENSE_EXPIRED2'            => " дней назад. Пожалуйста, перейдите на <a href='index.php?action=LicenseSettings&module=Administration'>'\"License Management\"</a> в панели администратора для указания нового лицензионного ключа. Если это не будет сделано в течение 30 дней с момента истечения срока лицензии, то вы не сможете войти в систему." ,
    'ERROR_MANIFEST_TYPE'               => 'В файле manifest.php  должен быть указан тип устанавливаемого пакета.' ,
    'ERROR_PACKAGE_TYPE'                => 'В файле manifest.php указан нераспознаваемый тип пакета.',
    'ERROR_VALIDATION_EXPIRED'          => 'Ошибка: Срок действия вашего ключа истек' ,
    'ERROR_VALIDATION_EXPIRED2'         => " дней назад. Пожалуйста, перейдите на <a href='index.php?action=LicenseSettings&module=Administration'>'\"License Management\"</a> в панели администратора для указания нового лицензионного ключа. Если это не будет сделано в течение 30 дней с момента истечения срока лицензии, то вы не сможете войти в систему." ,
    'ERROR_VERSION_INCOMPATIBLE'        => 'Загруженный файл не совместим с установленной версией Sugar Suite: ' ,

    'LBL_BACK'                          => 'Назад' ,
    'LBL_CANCEL'                        => 'Отмена',
    'LBL_ACCEPT'                        => 'Принимаю',
    'LBL_CHECKSYS_1'                    => 'Для того, чтобы установка SugarCRM работала правильно, пожалуйста убедитесь, что все нижерасположенные пункты окрашены в зеленый цвет. Если в списке присутствуют пункты, окрашенные в красный цвет, пожалуйста, выполните необходимые действия для устранения указанных ошибок.<BR><BR> За дополнительной справкой по этому вопросу Вы можете обратиться к <a href="http://www.sugarcrm.com/crm/installation" target="_blank">Sugar Wiki</a>' ,
    'LBL_CHECKSYS_CACHE'                => 'Доступные для записи подпапки папки Cache' ,
    //'LBL_CHECKSYS_CALL_TIME'          => 'Call Time Pass выключен' ,
    'LBL_DROP_DB_CONFIRM'               => 'База данных уже существует. Вы хотите продолжить и удалить текущие таблицы?  Будут уничтожены все существующие данные.',
    'LBL_CHECKSYS_CALL_TIME'            => 'Call Time Pass выключен' ,
    'LBL_CHECKSYS_COMPONENT'            => 'Основные компоненты' ,
    'LBL_CHECKSYS_COMPONENT_OPTIONAL'   => 'Дополнительные компоненты' ,
    'LBL_CHECKSYS_CONFIG'               => 'Доступный для записи файл config.php' ,
    'LBL_CHECKSYS_CURL'                 => 'Модуль cURL' ,
    'LBL_CHECKSYS_SESSION_SAVE_PATH'    => 'Настройка пути сохранения сессий',
    'LBL_CHECKSYS_CUSTOM'               => 'Доступная для записи пользовательская папка' ,
    'LBL_CHECKSYS_DATA'                 => 'Доступные для записи подпапки папки Data' ,
    'LBL_CHECKSYS_IMAP'                 => 'Модуль IMAP' ,
	'LBL_CHECKSYS_FASTCGI'              => 'FastCGI',
    'LBL_CHECKSYS_MQGPC'                => 'Magic Quotes GPC' ,
    'LBL_CHECKSYS_MBSTRING'             => 'Модуль MB Strings' ,
    'LBL_CHECKSYS_MEM_OK'               => 'ОК (нет ограничения)' ,
    'LBL_CHECKSYS_MEM_UNLIMITED'        => 'ОК (ограниченно)' ,
    'LBL_CHECKSYS_MEM'                  => 'Лимит памяти PHP' ,
    'LBL_CHECKSYS_MODULE'               => 'Доступные для записи подпапки и файлы модулей' ,
    'LBL_CHECKSYS_MYSQL_VERSION'        => 'Версия MySQL' ,
    'LBL_CHECKSYS_NOT_AVAILABLE'        => 'Недоступно' ,
    'LBL_CHECKSYS_OK'                   => 'OK' ,
    'LBL_CHECKSYS_PHP_INI'              => 'Расположение файла php.ini: ' ,
    'LBL_CHECKSYS_PHP_OK'               => 'OK (ver ' ,
    'LBL_CHECKSYS_PHPVER'               => 'Версия PHP' ,
	'LBL_CHECKSYS_IISVER'               => 'Версия IIS',
    'LBL_CHECKSYS_FASTCGI'              => 'FastCGI',
    'LBL_CHECKSYS_RECHECK'              => 'Проверить' ,
    'LBL_CHECKSYS_SAFE_MODE'            => 'PHP Safe Mode выключен' ,
    'LBL_CHECKSYS_SESSION'              => 'Доступная для записи папка для сохранения файлов сессий (' ,
    'LBL_CHECKSYS_STATUS'               => 'Статус' ,
    'LBL_CHECKSYS_TITLE'                => 'Проверка системных требований' ,
    'LBL_CHECKSYS_VER'                  => 'Найдено: ( версия ' ,
    'LBL_CHECKSYS_XML'                  => 'XML-парсинг' ,
    'LBL_CHECKSYS_ZLIB'                 => 'Модуль ZLIB' ,
    'LBL_CHECKSYS_FIX_FILES'            => 'Пожалуйста, настройте права доступа к следующим файлам/папкам:',
    'LBL_CHECKSYS_FIX_MODULE_FILES'     => 'Пожалуйста, настройте права доступа к следующим модулям и содержащимся в них файлам:',
    'LBL_CLOSE'                         => 'Закрыть' ,
    'LBL_THREE'                         => '3', ////
    'LBL_CONFIRM_BE_CREATED'            => 'будет создана' ,
    'LBL_CONFIRM_DB_TYPE'               => 'Тип базы данных' ,
    'LBL_CONFIRM_DIRECTIONS'            => 'Пожалуйста, проверьте указанные параметры. Если вы хотите исправить какой-либо параметр, нажмите кнопку "Назад" , если все в порядке - нажмите кнопку "Вперед" для начала процесса установки.' ,
    'LBL_CONFIRM_LICENSE_TITLE'         => 'Лицензионная информация' ,
    'LBL_CONFIRM_NOT'                   => 'не' ,
    'LBL_CONFIRM_TITLE'                 => 'Подтверждение параметров' ,
    'LBL_CONFIRM_WILL'                  => '' ,
    'LBL_DBCONF_CREATE_DB'              => 'Создать базу данных' ,
    'LBL_DBCONF_CREATE_USER'            => 'Создать пользователей' ,
    'LBL_DBCONF_DB_DROP_CREATE_WARN'    => 'Осторожно: все данные будут удалены, <br> если установить этот параметр.' ,
    'LBL_DBCONF_DB_DROP_CREATE'         => 'Удалить и создать заново таблицы Sugar?' ,
    'LBL_DBCONF_DB_DROP'                => 'Удаление таблиц',
    'LBL_DBCONF_DB_NAME'                => 'Название базы данных' ,
    'LBL_DBCONF_DB_PASSWORD'            => 'Пароль базы данных' ,
    'LBL_DBCONF_DB_PASSWORD2'           => 'Повтор пароля базы данных' ,
    'LBL_DBCONF_DB_USER'                => 'Имя пользователя базы данных' ,
    'LBL_DBCONF_SUGAR_DB_USER'          => 'Имя пользователя базы данных Sugar',
    'LBL_DBCONF_DB_ADMIN_USER'          => 'Логин администратора базы данных',
    'LBL_DBCONF_DB_ADMIN_PASSWORD'      => 'Пароль администратора базы данных',
    'LBL_DBCONF_DEMO_DATA'              => 'Заполнить базу данных демонстрационными данными?' ,
    'LBL_DBCONF_DEMO_DATA_TITLE'        => 'Демонстрация',
    'LBL_DBCONF_HOST_NAME'              => 'Хост' ,
    'LBL_DBCONF_HOST_NAME_MSSQL'        => 'Host Name \ Host Instance',
    'LBL_DBCONF_INSTRUCTIONS'           => 'Пожалуйста, настройте вашу базу данных. Если вы не уверены во вводимых данных, то мы советуем вам оставить значения по умолчанию.' ,
    'LBL_DBCONF_MB_DEMO_DATA'           => 'Использовать мультибайтовые символы в демонстрационных данных?' ,
    'LBL_DBCONFIG_MSG2'                 => 'Укажите имя сервера, на котором расположена ваша база данных (localhost - если БД расположена на одном сервере с файлами системы).',
    'LBL_DBCONFIG_MSG3'                 => 'Укажите название базы данных.',
    'LBL_DBCONFIG_B_MSG1'               => 'Укажите логин и пароль администратора базы данных. Администратор должен иметь соответствующие права на создание и запись в базе данных SugarCRM.',
    'LBL_DBCONFIG_SECURITY'             => 'В целях безопасности, необходим пользователь с административными,  эксклюзивными правами доступа к базе данных SugarCRM.  Этот пользователь может быть создан сейчас или же вы можете указать уже существующего пользователя.',
    'LBL_DBCONFIG_AUTO_DD'              => 'Do it for me',
    'LBL_DBCONFIG_PROVIDE_DD'           => 'Указать существующего пользователя',
    'LBL_DBCONFIG_CREATE_DD'            => 'Создать пользователя',
    'LBL_DBCONFIG_SAME_DD'              => 'Создать из администратора',
    //'LBL_DBCONF_I18NFIX'              => 'Apply database column expansion for varchar and char types (up to 255) for multi-byte data?',
    'LBL_MSSQL_FTS'                     => 'Полнотекстовый поиск',
    'LBL_MSSQL_FTS_INSTALLED'           => 'Установлен',
    'LBL_MSSQL_FTS_INSTALLED_ERR1'      => 'Полнотекстовый поиск не установлен.',
    'LBL_MSSQL_FTS_INSTALLED_ERR2'      => 'Вы можете установить полнотекстовый поиск, но не сможете им воспользоваться до тех пор, пока не будет переустановлен SQL Server с включенным полнотекстовым поиском. Обратитесь к руководству по Sql Server или свяжитесь с администратором.',

    'LBL_DBCONF_PRIV_PASS'              => 'Пароль администратора БД' ,
    'LBL_DBCONF_PRIV_USER_2'            => 'Введенное выше имя пользователя БД - это логин администратора?' ,
    'LBL_DBCONF_PRIV_USER_DIRECTIONS'   => 'Администратор (или привилегированный пользователь) должен иметь права на создание баз данных, удаление и создание таблиц, создание пользователей. Этот пользователь будет использован только для выполнения указанных задач в процессе установки. Вы также можете указать другого пользователя, если он имеет достаточные привилегии.' ,
    'LBL_DBCONF_PRIV_USER'              => 'Имя администратора (привилегированного пользователя)' ,
    'LBL_DBCONF_TITLE'                  => 'Конфигурация базы данных' ,
    'LBL_DBCONF_TITLE_NAME'             => 'Название базы данных',
    'LBL_DBCONF_TITLE_USER_INFO'        => 'Информация о пользователе базы данных',
    'LBL_DISABLED_DESCRIPTION_2'        => 'После того, как все изменения были сделаны, вы можете нажать на кнопку "Пуск" для начала процесса установки. По окончании установки  значение переменной \'installer_locked\' должно быть равно \'true\'.' ,
    'LBL_DISABLED_DESCRIPTION'          => 'Инсталлятор уже был однажды запущен. В целях безопасности возможность повторного запуска инсталлятора отключена. Если вы абсолютно уверены, что хотите запустить его еще раз, пожалуйста, в файле config.php установите значение переменной \'installer_locked\' в  \'false\'. Строка должна выглядеть следующим образом:' ,
    'LBL_DISABLED_HELP_1'               => 'За дополнительной информацией о процессе установки обращайтесь на сайт SugarCRM<br>' ,
    'LBL_DISABLED_HELP_LNK'               => 'http://www.sugarcrm.com/forums/',
    'LBL_DISABLED_HELP_2'               => 'Форумы поддержки' ,
    'LBL_DISABLED_HELP_LNK3'            => 'http://www.sugarcrm.com.ua',
    'LBL_DISABLED_HELP_3'               => 'Русскоязычный форум, посвященный SugarCRM' ,
    'LBL_DISABLED_TITLE_2'              => 'Установка SugarCRM приостановлена' ,
    'LBL_DISABLED_TITLE'                => 'Возможность установки SugarCRM отключена' ,
    'LBL_EMAIL_CHARSET_DESC'            => 'Установите наиболее часто используемую кодировку' ,
    'LBL_EMAIL_CHARSET_TITLE'           => 'Кодировка исходящей почты' ,
    'LBL_EMAIL_CHARSET_CONF'            => 'Кодировка исходящей почты',
    'LBL_HELP'                          => 'Помощь' ,
    'LBL_INSTALL'                       => 'Установить',
    'LBL_INSTALL_TYPE_TITLE'            => 'Параметры установки',
    'LBL_INSTALL_TYPE_SUBTITLE'         => 'Выберите тип установки',
    'LBL_INSTALL_TYPE_TYPICAL'          => 'Обычная установка',
    'LBL_INSTALL_TYPE_CUSTOM'           => 'Выборочная установка',
    'LBL_INSTALL_TYPE_MSG1'             => 'This key is not required for installation but will be required for general application functionality.  You will be able to enter it after you have installed and logged into the application.',
    'LBL_INSTALL_TYPE_MSG2'             => 'Необходимо минимум информации для установки. Рекомендуется для начинающих пользователей.',
    'LBL_INSTALL_TYPE_MSG3'             => 'Предоставляет дополнительные параметры для настройки процесса установки. Эти параметры так же будут доступны по окончании процесса установки в панели администратора. Рекомендуется для опытных пользователей.',
    'LBL_LANG_1'                        => 'Вы можете или установить языковой пакет, отличающийся от установленного по умолчанию (US-English), или нажать на кнопку "Вперед" для продолжения процесса установки.' ,
    'LBL_LANG_BUTTON_COMMIT'            => 'Установить' ,
    'LBL_LANG_BUTTON_REMOVE'            => 'Удалить' ,
    'LBL_LANG_BUTTON_UNINSTALL'         => 'Деинсталлировать' ,
    'LBL_LANG_BUTTON_UPLOAD'            => 'Загрузка' ,
    'LBL_LANG_NO_PACKS'                 => 'Нет установленных пакетов' ,
    'LBL_LANG_PACK_INSTALLED'           => 'Следующие языковые пакеты были установлены: ' ,
    'LBL_LANG_PACK_READY'               => 'Следующие языковые пакеты готовы к установке: ' ,
    'LBL_LANG_SUCCESS'                  => 'Языковой пакет успешно загружен' ,
    'LBL_LANG_TITLE'                    => 'Языковой пакет' ,
    'LBL_LAUNCHING_SILENT_INSTALL'      => 'Производится установка Sugar. Это может занять некоторое время.',
	'LBL_LANG_UPLOAD'                   => 'Загрузить языковой пакет' ,
    'LBL_LICENSE_ACCEPTANCE'            => 'Лицензионное соглашение' ,
    'LBL_LICENSE_CHECKING'              => 'Проверка совместимости',
    'LBL_LICENSE_CHKENV_HEADER'         => 'Проверка системного окружения',
    'LBL_LICENSE_CHKDB_HEADER'          => 'Проверка прав доступа к БД',
    'LBL_LICENSE_CHECK_PASSED'          => 'Проверка совместимости успешно пройдена',
    'LBL_LICENSE_REDIRECT'              => 'Перенаправление через ',
    'LBL_LICENSE_DIRECTIONS'            => 'Если у вас есть лицензионная информация, пожалуйста, введите ее в указанные поля.' ,
    'LBL_LICENSE_DOWNLOAD_KEY'          => 'Загрузить ключ' ,
    'LBL_LICENSE_EXPIRY'                => 'Дата окончания' ,
    'LBL_LICENSE_I_ACCEPT'              => 'Я принимаю лицензионное соглашение' ,
    'LBL_LICENSE_NUM_USERS'             => 'Количество пользователей' ,
    'LBL_LICENSE_OC_DIRECTIONS'         => 'Пожалуйста, укажите количество купленных рабочих мест.' ,
    'LBL_LICENSE_OC_NUM'                => 'Количество лицензий на рабочие места' ,
    'LBL_LICENSE_OC'                    => 'Лицензии на рабочие места' ,
    'LBL_LICENSE_PRINTABLE'             => 'Версия для печати' ,
    'LBL_PRINT_SUMM'                    => 'Печать',
    'LBL_LICENSE_TITLE_2'               => 'Лицензия SugarCRM' ,
    'LBL_LICENSE_TITLE'                 => 'Лицензионная информация' ,
    'LBL_LICENSE_USERS'                 => 'Лицензированные пользователи' , ////
    'LBL_LOCALE_CURRENCY'               => 'Установки валюты' ,
    'LBL_LOCALE_CURR_DEFAULT'           => 'Валюта по умолчанию' ,
    'LBL_LOCALE_CURR_SYMBOL'            => 'Символ валюты' ,
    'LBL_LOCALE_CURR_ISO'               => 'Код валюты (ISO 4217)' ,
    'LBL_LOCALE_CURR_1000S'             => 'Разделитель групп разрядов' ,
    'LBL_LOCALE_CURR_DECIMAL'           => 'Десятичный разделитель' ,
    'LBL_LOCALE_CURR_EXAMPLE'           => 'Пример' ,
    'LBL_LOCALE_CURR_SIG_DIGITS'        => 'Значащие разряды' ,
    'LBL_LOCALE_DATEF'                  => 'Формат даты по умолчанию' ,
    'LBL_LOCALE_DESC'                   => 'Укажите региональные настройки' ,
    'LBL_LOCALE_EXPORT'                 => 'Кодировка для импорта/экспорта (E-mail, .csv, vCard)' ,
    'LBL_LOCALE_EXPORT_DELIMITER'       => 'Разделитель .csv при экспорте' ,
    'LBL_LOCALE_EXPORT_TITLE'           => 'Установки экспорта' ,
    'LBL_LOCALE_LANG'                   => 'Язык по умолчанию' ,
    'LBL_LOCALE_NAMEF'                  => 'Формат имен по умолчанию' ,
    'LBL_LOCALE_NAMEF_DESC'             => 's - приветствие f - Имя l - Фамилия' ,
    'LBL_LOCALE_NAME_FIRST'             => 'Афиноген' ,
    'LBL_LOCALE_NAME_LAST'              => 'Пупкин' ,
    'LBL_LOCALE_NAME_SALUTATION'        => 'Гн.' ,
    'LBL_LOCALE_TIMEF'                  => 'Формат времени по умолчанию' ,
    'LBL_LOCALE_TITLE'                  => 'Региональные настройки' ,
    'LBL_CUSTOMIZE_LOCALE'              => 'Локализация',
    'LBL_LOCALE_UI'                     => 'Пользовательский интерфейс' ,
	
    'LBL_ML_ACTION'                     => 'Действие' ,
    'LBL_ML_DESCRIPTION'                => 'Описание' ,
    'LBL_ML_INSTALLED'                  => 'Дата установки' ,
    'LBL_ML_NAME'                       => 'Имя' ,
    'LBL_ML_PUBLISHED'                  => 'Дата публикации' ,
    'LBL_ML_TYPE'                       => 'Тип' ,
    'LBL_ML_UNINSTALLABLE'              => 'Деинсталляция' ,
    'LBL_ML_VERSION'                    => 'Версия' ,
    'LBL_MSSQL'                         => 'MS SQL Server' ,
    'LBL_MSSQL2'                        => 'SQL Server (FreeTDS)',
    'LBL_MYSQL'                         => 'MySQL' ,
    'LBL_NEXT' => 'Вперед',
    'LBL_NO' => 'Нет',
    'LBL_ORACLE' => 'Oracle', ////
    'LBL_PERFORM_ADMIN_PASSWORD'        => 'Setting site admin password' ,
    'LBL_PERFORM_AUDIT_TABLE'           => 'audit table / ' ,
    'LBL_PERFORM_CONFIG_PHP'            => 'Creating Sugar configuration file' ,
    'LBL_PERFORM_CREATE_DB_1'           => 'Creating the database ' ,
    'LBL_PERFORM_CREATE_DB_2'           => 'on ' ,
    'LBL_PERFORM_CREATE_DB_USER'        => 'Creating the Database username and password...' ,
    'LBL_PERFORM_CREATE_DEFAULT'        => 'Creating default Sugar data' ,
    'LBL_PERFORM_CREATE_LOCALHOST'      => 'Creating the Database username and password for localhost...' ,
    'LBL_PERFORM_CREATE_RELATIONSHIPS'  => 'Creating Sugar relationship tables' ,
    'LBL_PERFORM_CREATING'              => 'creating / ' ,
    'LBL_PERFORM_DEFAULT_REPORTS'       => 'Creating default reports' ,
    'LBL_PERFORM_DEFAULT_SCHEDULER'     => 'Creating default scheduler jobs' ,
    'LBL_PERFORM_DEFAULT_SETTINGS'      => 'Inserting default settings' ,
    'LBL_PERFORM_DEFAULT_USERS'         => 'Creating default users' ,
    'LBL_PERFORM_DEMO_DATA'             => 'Populating the database tables with demo data (this may take a little while)' ,
    'LBL_PERFORM_DONE'                  => 'done' ,
    'LBL_PERFORM_DROPPING'              => 'dropping / ' ,
    'LBL_PERFORM_FINISH'                => 'Готово' ,
    'LBL_PERFORM_LICENSE_SETTINGS'      => 'Updating license information' ,
    'LBL_PERFORM_OUTRO_1'               => 'Установка Sugar ' ,
    'LBL_PERFORM_OUTRO_2'               => ' завершена.' ,
    'LBL_PERFORM_OUTRO_3'               => 'Установка заняла ' ,
    'LBL_PERFORM_OUTRO_4'               => ' секунд.' ,
    'LBL_PERFORM_OUTRO_5'               => 'Приблизительно использовано памяти: ' ,
    'LBL_PERFORM_OUTRO_6'               => ' байт.' ,
    'LBL_PERFORM_OUTRO_7'               => 'Система установлена и готова к использованию.' ,
    'LBL_PERFORM_REL_META'              => 'relationship meta ... ' ,
    'LBL_PERFORM_SUCCESS'               => 'Success!' ,
    'LBL_PERFORM_TABLES'                => 'Creating Sugar application tables, audit tables, and relationship metadata...' ,
    'LBL_PERFORM_TITLE'                 => 'Выполнение установки' ,
    'LBL_PRINT'                         => 'Печатать...' ,
    'LBL_REG_CONF_1'                    => 'Пожалуйста, потратьте немного вашего драгоценнейшего времени для заполнения указанной формы и регистрации установленной версии SugarCRM. Полученная от вас информация НЕ будет передана третьим лицам.' ,
    'LBL_REG_CONF_2'                    => 'Для регистрации необходимы ваше полное имя и адрес электронной почты. <br>Другие поля необязательны для заполнения.' ,
    'LBL_REG_CONF_3'                    => 'Спасибо за регистрацию. Нажмите на кнопку "Завершить"  для того, чтобы начать работу в SugarCRM. Для первого входа в систему вам понадобятся логин и пароль, которые вы указали на 2 шаге установки системы.' ,
    'LBL_REG_TITLE'                     => 'Регистрация' ,
    'LBL_REG_NO_THANKS'                 => 'Не регистрироваться',
    'LBL_REG_SKIP_THIS_STEP'            => 'Пропустить этот шаг',
    'LBL_REQUIRED'                      => '* Поля, обязательные для заполнения' ,

    'LBL_SITECFG_ADMIN_Name'            => 'Имя администратора системы',
    'LBL_SITECFG_ADMIN_PASS_2'          => 'Повторный ввод пароля администратора' ,
    'LBL_SITECFG_ADMIN_PASS_WARN'       => 'Осторожно: произойдет перезапись пароля администратора любой предыдущей установки SugarCRM.' ,
    'LBL_SITECFG_ADMIN_PASS'            => 'Пароль <em>администратора</em>' ,
    'LBL_SITECFG_APP_ID'                => 'Код приложения' ,
    'LBL_SITECFG_CUSTOM_ID_DIRECTIONS'  => ' Перезапись сгенерированного кода приложения предотвращает доступ к новому экземпляру приложения из уже запущенного приложения. Если вы используете несколько копий SugarCRM, то у них должен быть <u>идентичный</u> код приложения.' ,
    'LBL_SITECFG_CUSTOM_ID'             => 'Укажите ваш личный код приложения' ,
    'LBL_SITECFG_CUSTOM_LOG_DIRECTIONS' => 'Перезапись папку по умолчанию, где находится файл журнала. Не важно, где находится этот файл, доступ браузера к нему будет ограничен правилами, указанными в файле .htaccess.' ,
    'LBL_SITECFG_CUSTOM_LOG'            => 'Использовать другую папку для файла журнала' ,
    'LBL_SITECFG_CUSTOM_SESSION_DIRECTIONS' => 'Создание отдельной папки для сохранения файлов сессий с целью увеличения степени надежности сохранения сессионных данных.' ,
    'LBL_SITECFG_CUSTOM_SESSION'        => 'Использовать другую папку для записи файлов сессий' ,
    'LBL_SITECFG_DIRECTIONS'            => 'Пожалуйста, настройте ваш сайт. Если вы не уверены в вводимых данных, то мы советуем вам оставить значения по умолчанию.' ,
    'LBL_SITECFG_FIX_ERRORS'            => 'Пожалуйста, исправьте следующие ошибки:' ,
    'LBL_SITECFG_LOG_DIR'               => 'Папка файла журнала' ,
    'LBL_SITECFG_SESSION_PATH'          => 'Папка файлов сессий (должна быть доступна для записи)' ,
    'LBL_SITECFG_SITE_SECURITY'         => 'Дополнительные параметры защиты' ,
    'LBL_SITECFG_SUGAR_UP_DIRECTIONS'   => 'Система периодически проверяет наличие доступных обновлений.' ,
    'LBL_SITECFG_SUGAR_UP'              => 'Проверять доступные обновления автоматически?' ,
    'LBL_SITECFG_SUGAR_UPDATES'         => 'Настройка процесса обновления Sugar' ,
    'LBL_SITECFG_TITLE'                 => 'Конфигурация сайта' ,
    'LBL_SITECFG_TITLE2'                => 'Параметры SugarCRM',
    'LBL_SITECFG_SECURITY_TITLE'        => 'Параметры безопасности',
    'LBL_SITECFG_URL'                   => 'URL дистрибутива Sugar ' ,
    'LBL_SITECFG_USE_DEFAULTS'          => 'Использовать стандартные установки?' ,
    'LBL_SITECFG_ANONSTATS'             => 'Отсылать анонимную статистику использования данного программного обеспечения?' ,
    'LBL_SITECFG_ANONSTATS_DIRECTIONS'  => 'Sugar отсылает анонимную статистику использования данного программного продукта в SugarCRM Inc. каждый раз, когда система проверяет наличие доступных обновлений. Эта информация  поможет нам лучше понять, каким образом используется приложение, и, как следствие,  значительно улучшить программный продукт.' ,
    'LBL_SITECFG_URL_MSG'               => 'Введите стартовый URL приложения. Например, ввод значения "localhost" означает разрешенный доступ к системе только с этого компьютера.',
    'LBL_SITECFG_SYS_NAME_MSG'          => 'Введите название системы. Это название будет отображаться в заголовке браузера при работе пользователей в приложении.',
    'LBL_SITECFG_PASSWORD_MSG'          => 'После установки системы необходимо войти в Sugar под учетной записью администратора . После входа в систему вы можете сменить указанные при установке логин и пароль администратора системы.',
    'LBL_SYSTEM_CREDS'                  => 'Параметры доступа',
    'LBL_SYSTEM_ENV'                    => 'Системное окружение',
    'LBL_START'                         => 'Пуск' ,
    'LBL_SHOW_PASS'                     => 'Показать пароли',
    'LBL_HIDE_PASS'                     => 'Спрятать пароли',
    'LBL_HIDDEN'                        => '<i>(hidden)</i>',
//  'LBL_NO_THANKS'                     => 'Continue to installer',
    'LBL_CHOOSE_LANG'                   => 'Выберите используемый в системе язык',
    'LBL_STEP'                          => 'Шаг' ,
    'LBL_TITLE_WELCOME'                 => 'Добро пожаловать в SugarCRM ' ,
    'LBL_WELCOME_1'                     => 'Данная программа установки создает таблицы базы данных, а так же настраивает конфигурационные переменные, необходимые для начала работы с системой. Процесс установки займет не более 10 минут.' ,
    'LBL_WELCOME_2'                     => 'За дополнительной информацией о процессе установки SugarCRM Вы можете обратиться как в <a href="http://www.sugarcrm.com/crm/installation" target="_blank">Sugar Wiki</a>, так и на <a href="http://www.sugarcrm.com/forums/" target="_blank">форумы поддержки</a>, а так же на <a href="http://www.sugarcrm.com.ua/" target="_blank">Русскоязычный форум, посвященный SugarCRM</a>.' ,
//welcome page variables
    'LBL_TITLE_ARE_YOU_READY' => 'Вы готовы к установке?',
    'REQUIRED_SYS_COMP' => 'Необходимые системные компоненты',
    'REQUIRED_SYS_COMP_MSG' =>  'Перед тем как продолжить, пожалуйста, убедитесь, что у вас установлены поддерживаемые версии следующих системных компонентов:<br>
                      <ul>


                      <li> База данных/СУБД (MySQL, SQL Server, Oracle)</li>
                      <li> Web-сервер (Apache, IIS) </li>
                      </ul>
                      Обратитесь к разделу <b>Compatibility Matrix</b>, находящемуся в примечаниях к релизу, по поводу совместимости системных компонентов и устанавливаемой версии системы.<br>',
    'REQUIRED_SYS_CHK' => 'Проверка системы',
    'REQUIRED_SYS_CHK_MSG' =>
                    'В начале процесса установки на сервере будет выполнена проверка системы, чтобы убедиться, что все компоненты, необходимые для успешной установки Sugar, установлены и правильно настроены. <br><br>
                      Система проверит следующие компоненты:<br>
                                            <ul>
                      <li><b>Версия PHP</b> &#8211; должна быть совместима с приложением</li>
                                        <li><b>Переменные сессии</b> &#8211; должны работать правильно</li>
                                            <li> <b>MB Strings</b> &#8211; расширение должно быть установлено и включено в php.ini</li>
                        <li> <b>Поддержка баз данных</b> &#8211; должна присутствовать для MySQL, SQL
                      Server или Oracle</li>

                      <li> <b>Config.php</b> &#8211; должен существовать и иметь соответствующие права на запись              </li>
		      <li>Следующие папки системы должны быть доступны для записи:<ul><li><b>/custom</li>

<li>/cache</li>
<li>/modules</b></li></ul></li></ul>
                                  Если проверка не будет пройдена, вы не сможете продолжить установку системы. В этом случае появится сообщение, объясняющее, по каким причинам проверка не была пройдена. После выполнения всех необходимых изменений вы можете запустить проверку еще раз для продолжения установки системы.<br><br>',

    'REQUIRED_INSTALLTYPE' => 'Обычная или выборочная установка',
    'REQUIRED_INSTALLTYPE_MSG' =>
                    'После выполнения проверки системы вы можете выбрать обычную или выборочную установку.<br><br>
                     И для <b>обычной</b> и для <b>выборочной</b> установки вам необходимо знать следующее:<br>
                      <ul>
                      <li> <b>Тип базы данных</b>, в которой будут храниться данные. <ul><li>Поддерживаемые типы: MySQL, MS SQL Server, Oracle.<br><br></li></ul></li>
                      <li> <b>Название web-сервера</b> или имя компьютера (хоста), на котором находится база данных.<ul><li>Это может быть <i>localhost</i>, если БД расположена на вашем компьютере или на том же сервере, где и файлы Sugar.<br><br></li></ul></li>
                      <li><b>Название базы данных</b>, которую вы хотите использовать для хранения данных.</li>
                        <ul>
                          <li> Возможно, база данных, которую вы хотите использовать уже существует. Если вы укажете имя уже существующей базы, все таблицы из этой базы будут удалены в процессе установки, когда будет определяться схема базы данных Sugar.</li>
                          <li> Если база данных еще не существует, указанное вами имя будет использоваться при создании новой базы данных в процессе установки системы.<br><br></li>
                        </ul>
                      <li><b>Логин и пароль администратора базы данных.</b> <ul><li>Администратор базы данных должен иметь права на создание таблиц и пользователей, а так же на запись в базу данных.</li><li>Свяжитесь с вашим администратором, если база данных расположена не на вашем компьютере и/или вы не являетесь администратором базы данных.<br><br></ul></li></li>
                      <li> <b>Логин и пароль пользователя системы.</b>
                      </li>
                        <ul>
                          <li> Это может быть логин администратора базы данных; вы также можете указать логин другого существующего пользователя базы данных. </li>
                          <li> Если вы хотите создать нового пользователя базы данных, вы сможете указать его логин и пароль в процессе установки. </li>
                        </ul></ul><p>

                      Для <b>выборочной</b> установки вам, возможно, потребуется знать следующее:<br>
                      <ul>
                      <li> <b>URL, который будет использоваться для доступа к установленной версии Sugar.</b>
                      URL будет содержать имя сервера или компьютера или же IP-адрес.<br><br></li>
                                  <li> [Выборочно] <b>Путь к папке с сессиями</b>, если вы захотите использовать свою собственную папку во избежание уязвимости системы при использовании общих серверов.<br><br></li>
                                  <li> [Выборочно] <b>Путь к папке журнала</b>, если вы захотите использовать папку, отличную от установленной по умолчанию.<br><br></li>
                                  <li> [Выборочно] <b>ID приложения</b>, если вы хотите перезаписать автоматически сгенерированный идентификатор приложения, который гарантирует, что сессии одного экземпляра системы не будут использоваться другими экземплярами Sugar.<br><br></li>
                                  <li><b>Кодировку</b>, наиболее часто используемую в системе.<br><br></li></ul>
                                  За более подробной информацией обратитесь к руководству пользователя.',

    'LBL_WELCOME_PLEASE_READ_BELOW' => 'Пожалуйста, прочтите следующую информацию перед началом установки. Данная информация поможет вам определить, готовы ли вы к установке Sugar.',




    'LBL_WELCOME_CHOOSE_LANGUAGE'       => 'Выберите языковой файл' ,
    'LBL_WELCOME_SETUP_WIZARD'          => 'Мастер установки' ,
    'LBL_WELCOME_TITLE_WELCOME'         => 'Добро пожаловать в SugarCRM' ,
    'LBL_WELCOME_TITLE'                 => 'Мастер установки SugarCRM ' ,
    'LBL_WIZARD_TITLE'                  => 'Мастер установки SugarCRM: Шаг ' ,
    'LBL_YES'                           => 'Да' ,
    'LBL_YES_MULTI'                     => 'Да - Multibyte',
    // OOTB Scheduler Job Names:
    'LBL_OOTB_WORKFLOW'     => 'Обработка задач документооборота' ,
    'LBL_OOTB_REPORTS'      => 'Выполнять запланированные задачи создания отчётов' ,
    'LBL_OOTB_IE'           => 'Проверить входящие письма' ,
    'LBL_OOTB_BOUNCE'       => 'Возвращать письмо отправителю при неудачной рассылке' ,
    'LBL_OOTB_CAMPAIGN'     => 'Запускать ночью массовую рассылку писем' ,
    'LBL_OOTB_PRUNE'        => 'Очищать базу данных первого числа каждого месяца',
    'LBL_OOTB_TRACKER'      => 'Очищать таблицы трекера',
    'LBL_UPDATE_TRACKER_SESSIONS' => 'Обновить таблицу tracker_sessions',
    'LBL_PATCHES_TITLE'     => 'Установить последние обновления',
    'LBL_MODULE_TITLE'      => 'Установить языковые пакеты',
    'LBL_PATCH_1'           => 'Если вы желаете пропустить этот шаг, пожалуйста, нажмите на кнопку "Вперед >>".',
    'LBL_PATCH_TITLE'       => 'Обновление системы',
    'LBL_PATCH_READY'       => 'Следующие обновления готовы к установке:',
    'LBL_SESSION_ERR_DESCRIPTION'=> "SugarCRM использует механизм сессий для сохранения важной информации при подключении к web-серверу. При установке PHP информация о сессиях не была сконфигурирована должным образом; возможно, переменная <b>'session.save_path'</b> не указывает на существующую папку.<br>Для устранения ошибки обратитесь к <a target=_new href='http://us2.php.net/manual/en/ref.session.php'>соответствующему разделу файла php.ini</a>.",

    'LBL_SESSION_ERR_TITLE' => 'Ошибка в настройке сессий PHP',
    'LBL_SYSTEM_NAME' => 'Название системы',
    'LBL_REQUIRED_SYSTEM_NAME' => 'Название системы не может быть пустым',
    'LBL_PATCH_UPLOAD' => 'Загрузить обновление',
    'LBL_INCOMPATIBLE_PHP_VERSION' => 'Требуется PHP версии 5 или выше.',
    'LBL_MINIMUM_PHP_VERSION' => 'Минимальная версия PHP - 5.1.0. Рекомендуемая версия PHP - 5.2.x.',
    'LBL_YOUR_PHP_VERSION' => '(Установленная версия PHP: ',
    'LBL_RECOMMENDED_PHP_VERSION' =>' Рекомендуемая версия PHP: 5.2.x)',
    'LBL_BACKWARD_COMPATIBILITY_ON' => 'В PHP включен режим обратной совместимости. Для продолжения отключите параметр zend.ze1_compatibility_mode',
	'LBL_CHECKSYS_VARIABLE_ORDER_TITLE' => 'Порядок обработки переменных',
    'LBL_CHECKSYS_VARIABLE_ORDER_INFO' => 'В системе используются суперглобальные массивы. Присвойте переменной variables_order значение "EGPCS"',

	);


?>