<?php
if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');
/*********************************************************************************
 * SugarCRM is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004 - 2010 SugarCRM Inc.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo. If the display of the logo is not reasonably feasible for
 * technical reasons, the Appropriate Legal Notices must display the words
 * "Powered by SugarCRM".
 ********************************************************************************/

  /*********************************************************************************
  *
  * File generated by the RAPIRA Translation Suite ----------
  *
  ***********************************************************************likhobory*/

  /*********************************************************************************
  * Description : Defines the Russian language pack for the base application.
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s):
  *********************************************************************************/

$mod_strings = array (
'LBL_MODULE_NAME' => 'Диаграммы' ,
'LBL_MODULE_TITLE' => 'Диаграммы - ГЛАВНАЯ' ,
'LNK_NEW_ACCOUNT' => 'Создать контрагента' ,
'LNK_NEW_CALL' => 'Назначить звонок' ,
'LNK_NEW_CASE' => 'Создать обращение' ,
'LNK_NEW_CONTACT' => 'Создать контакт' ,
'LNK_NEW_ISSUE' => 'Новая ошибка' ,
'LNK_NEW_LEAD' => 'Создать предв. контакт' ,
'LNK_NEW_MEETING' => 'Назначить встречу' ,
'LNK_NEW_NOTE' => 'Создать заметку или вложение' ,
'LNK_NEW_OPPORTUNITY' => 'Создать сделку' ,
'LNK_NEW_QUOTE' => 'Создать смету' ,
'LNK_NEW_TASK' => 'Создать задачу' ,

'LBL_ADD_A_CHART' => 'Добавить диаграмму' ,
'LBL_DELETE_FROM_DASHBOARD' => 'Удаление с панели' ,
'LBL_MOVE_DOWN' => 'Переместить вверх' ,
'LBL_MOVE_UP' => 'Переместить вниз' ,
'LBL_BASIC_CHARTS' => '-- Основные диаграммы --' ,
'LBL_PUBLISHED_REPORTS' => '-- Отчеты общей группы --' ,
'LBL_MY_REPORTS' => '-- Мои сохраненные отчёты --' ,
'LBL_TEAM_REPORTS' => '-- Мои групповые отчёты --' ,
'LBL_REPORT_NO_CHART' => 'У этого отчёта нет диаграммы' ,
'LBL_MOVE_CHARTS' => '(Кликните на названии диаграммы для того, чтобы переместить ее)' ,

'LBL_DASHBOARD_PAGE_1' => 'Диаграммы - ГЛАВНАЯ',
'LBL_DASHBOARD_PAGE_2' => 'Sales Dashboard',

);


?>