<?php
if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');
/*********************************************************************************
 * SugarCRM is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004 - 2010 SugarCRM Inc.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo. If the display of the logo is not reasonably feasible for
 * technical reasons, the Appropriate Legal Notices must display the words
 * "Powered by SugarCRM".
 ********************************************************************************/

  /*********************************************************************************
  *
  * File generated by the RAPIRA Translation Suite ----------
  *
  ***********************************************************************likhobory*/

  /*********************************************************************************
  * Description : Defines the Russian language pack for the base application.
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s):
  *********************************************************************************/

$mod_strings = array (
'ERR_DELETE_RECORD' => 'Вы должны указать номер записи перед удалением.' ,

'LBL_ACCOUNT_ID' => 'Код контрагента' ,
'LBL_ACCOUNT_NAME' => 'Контрагент:' ,
'LBL_ACCOUNTS_SUBPANEL_TITLE' => 'Контрагенты',
'LBL_ACTIVITIES_SUBPANEL_TITLE' => 'Мероприятия' ,
'LBL_ATTACH_NOTE' => 'Прикрепить заметку',
'LBL_BUGS_SUBPANEL_TITLE' => 'Ошибки' ,
'LBL_CASE_NUMBER' => 'Номер обращения:' ,
'LBL_CASE_SUBJECT' => 'Тема примера:' ,
'LBL_CASE' => 'Обращение:' ,
'LBL_CONTACT_CASE_TITLE' => 'Контакт обращения:' ,
'LBL_CONTACT_NAME' => 'Контактное лицо:' ,
'LBL_CONTACT_ROLE' => 'Роль:' ,
'LBL_CONTACTS_SUBPANEL_TITLE' => 'Контакты' ,
'LBL_DEFAULT_SUBPANEL_TITLE' => 'Обращения' ,
'LBL_DESCRIPTION' => 'Описание:' ,
'LBL_FILENANE_ATTACHMENT' => 'Вложение',
'LBL_HISTORY_SUBPANEL_TITLE' => 'История' ,
'LBL_INVITEE' => 'Контакты' ,
'LBL_MEMBER_OF' => 'Контрагент' ,
'LBL_MODULE_NAME' => 'Обращения' ,
'LBL_MODULE_TITLE' => 'Обращения - ГЛАВНАЯ' ,
'LBL_NEW_FORM_TITLE' => 'Новое обращение' ,
'LBL_NUMBER' => 'Номер:' ,
'LBL_PRIORITY' => 'Приоритет:' ,
'LBL_PROJECTS_SUBPANEL_TITLE' => 'Проекты',
'LBL_RESOLUTION' => 'Резолюция:' ,
'LBL_SEARCH_FORM_TITLE' => 'Поиск обращения' ,
'LBL_STATUS' => 'Статус:' ,
'LBL_SUBJECT' => 'Тема:' ,
'LBL_SYSTEM_ID' => 'System ID' ,
//'LBL_LIST_ASSIGNED_TO_NAME' 		=> 'Assigned User',
'LBL_LIST_ACCOUNT_NAME' => 'Контрагент' ,
'LBL_LIST_ASSIGNED' => 'Ответственный(ая)' ,
'LBL_LIST_CLOSE' => 'Закрыть' ,
'LBL_LIST_FORM_TITLE' => 'Список обращений' ,
'LBL_LIST_LAST_MODIFIED' => 'Последнее изменение' ,
'LBL_LIST_MY_CASES' => 'Мои открытые обращения' ,
'LBL_LIST_NUMBER' => 'Ном.' ,
'LBL_LIST_PRIORITY' => 'Приоритет' ,
'LBL_LIST_STATUS' => 'Статус' ,
'LBL_LIST_SUBJECT' => 'Тема' ,
'LBL_LIST_ASSIGNED_TO_NAME' => 'Ответственный(ая)',

'LNK_CASE_LIST' => 'Обращения' ,
'LNK_NEW_CASE' => 'Создать обращение' ,
'NTC_REMOVE_FROM_BUG_CONFIRMATION' => 'Вы действительно хотите удалить это обращение из данной ошибки?' ,
'NTC_REMOVE_INVITEE' => 'Вы действительно хотите удалить это контактное лицо из данного обращения?' ,
'LBL_LIST_ASSIGNED_TO_NAME' => 'Ответственный(ая)',
'LBL_ASSIGNED_TO_ID' =>'Ответственный(ая)',

'LBL_LIST_DATE_CREATED'	=> 'Дата создания',
'LBL_ASSIGNED_TO_NAME' => 'Ответственный(ая)',
'LBL_TYPE'=>'Тип',
'LBL_WORK_LOG'=>'Журнал',
'LNK_IMPORT_CASES' => 'Импорт обращений',

'LBL_CREATED_USER' => 'Создано',
'LBL_MODIFIED_USER' => 'Изменено',

'LBL_PROJECT_SUBPANEL_TITLE' => 'Проекты',
'LBL_CASE_INFORMATION' => 'Описание обращения',

);

?>