<?PHP
/*********************************************************************************
 * SugarCRM is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2011 SugarCRM Inc.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo. If the display of the logo is not reasonably feasible for
 * technical reasons, the Appropriate Legal Notices must display the words
 * "Powered by SugarCRM".
 ********************************************************************************/

/**
 * THIS CLASS IS GENERATED BY MODULE BUILDER
 * PLEASE DO NOT CHANGE THIS CLASS
 * PLACE ANY CUSTOMIZATIONS IN cosib_messages
 */


class cosib_messages_sugar extends Basic {
	var $new_schema = true;
	var $module_dir = 'cosib_messages';
	var $object_name = 'cosib_messages';
	var $table_name = 'cosib_messages';
	var $importable = false;
	var $disable_row_level_security = true ; // to ensure that modules created and deployed under CE will continue to function under team security if the instance is upgraded to PRO
		var $id;
		var $name;
		var $date_entered;
		var $date_modified;
		var $modified_user_id;
		var $modified_by_name;
		var $created_by;
		var $created_by_name;
		var $description;
		var $deleted;
		var $created_by_link;
		var $modified_user_link;
		var $assigned_user_id;
		var $assigned_user_name;
		var $assigned_user_link;
		function cosib_messages_sugar(){
		parent::Basic();
	}

	function bean_implements($interface){
		switch($interface){
			case 'ACL': return true;
		}
		return false;
}
   function answers_Save(){
	     global $db;
	     global $current_user;

	    $description = trim($_REQUEST["description"]);
	     if( strlen($description) >0 ){

		     $id_new = create_guid();
		     $answer = array(
		     	'id' => $id_new,
		     	'id_m' => $this->getFieldValue('id'),
		     	'description' =>  $description,
		     	'date_entered' => date('Y-m-d H:i:s'),
                'assigned_user_id' => $current_user->id,
                'first_name' => $current_user->first_name,
                'last_name' => $current_user->last_name,
		     );
		     $query = 'INSERT INTO cosib_messages_answers (id,id_m,description,date_entered,assigned_user_id)
		                 VALUES(\''.$answer["id"].'\',\''.$answer["id_m"].'\',\''.$db->quote($answer["description"]).'\',\''.$answer["date_entered"].'\',\''.$answer['assigned_user_id'].'\')';
		     $result = $db->query($query);
		     return $this->answer_html($answer);
		 }
         return '';

   }

   function answers_List(){
	     global $db;
	     $id = $this->getFieldValue('id');
	     $query = 'SELECT m.*,u.first_name,u.last_name FROM cosib_messages_answers m JOIN users u ON u.id=m.assigned_user_id
     			  WHERE m.id_m=\''.$id.'\' AND u.deleted=0 ORDER BY m.date_entered DESC';
         $result = $db->query($query);

         $lists = '';
         while($arrAnswer =$db->fetchByAssoc($result) ){
          	$lists .= $this->answer_html($arrAnswer);
         }
         return $lists;
   }

   function answers_DeleteRestore($delete=1){
	    global $db;
	    $id = $this->getFieldValue('id');
	    $query = 'UPDATE cosib_messages_answers SET deleted = '.$delete.' where id_m=\''.$id.'\'';
	    $result = $db->query($query,'Deleted answers');
   }
   function answer_html($answer){
   	global $mod_strings;
        $result='
            <table cellspacing="0" style="padding-bottom:10px">
			<tbody>
				<tr>
					<td width="10.5%" scope="row">
			         <B> '.$mod_strings['LBL_ANSWER_FIELD'].': </B>
					</td>
					<td width="50.5%" style="padding-left:6px">
					<span> '.$answer["description"].'</span>
					</td>
					<td width="12.5%" scope="row"> <B>'.$mod_strings['LBL_DATE_ENTERED'].': </B>
					</td  width="12.5%">
					<td style="padding-left:6px">
					 <span> '.$answer["date_entered"].'</span
					</td>
					<td width="5.5%" scope="row"> <B>'.$mod_strings['LBL_ASSIGNED_TO_NAME'].': </B>
					</td>
					<td style="padding-left:6px" >
					<span>  <a href = "index.php?action=DetailView&module=Users&record='.$answer['assigned_user_id'].'">'
					 	.$answer['first_name'].' '.$answer['last_name'].'</a>   </span
					</td>
				</tr>

			</tbody>
			</table>
        ';
       return $result;

   }


}
?>