<?php
if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');
/*********************************************************************************
 * SugarCRM is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004 - 2010 SugarCRM Inc.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo. If the display of the logo is not reasonably feasible for
 * technical reasons, the Appropriate Legal Notices must display the words
 * "Powered by SugarCRM".
 ********************************************************************************/

  /*********************************************************************************
  *
  * File generated by the RAPIRA Translation Suite ----------
  *
  ***********************************************************************likhobory*/

  /*********************************************************************************
  * Description : Defines the Russian language pack for the base application.
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s):
  *********************************************************************************/

$mod_strings = array (
'LBL_MODULE_NAME' => 'Главная',
'LBL_MODULES_TO_SEARCH' => 'Поиск в модулях:',
'LBL_NEW_FORM_TITLE' => 'Новый контакт' ,
'LBL_FIRST_NAME' => 'Имя:' ,
'LBL_LAST_NAME' => 'Фамилия:' ,
'LBL_LIST_LAST_NAME' => 'Фамилия' ,
'LBL_PHONE' => 'Тел.:' ,
'LBL_EMAIL_ADDRESS' => 'E-mail:' ,
'LBL_MY_PIPELINE_FORM_TITLE' => 'Диаграмма стадий моих продаж',
'LBL_PIPELINE_FORM_TITLE' => 'Диаграмма стадий общих продаж',
'LBL_CAMPAIGN_ROI_FORM_TITLE' => 'Рентабельность инвестиций',
'LBL_MY_CLOSED_OPPORTUNITIES_GAUGE' => 'My Closed Won Opportunities Gauge', ///
'LNK_NEW_CONTACT' => 'Создать контакт' ,
'LNK_NEW_ACCOUNT' => 'Создать контрагента' ,
'LNK_NEW_OPPORTUNITY' => 'Создать сделку' ,
'LNK_NEW_LEAD' => 'Создать предв. контакт' ,
'LNK_NEW_CASE' => 'Создать обращение' ,
'LNK_NEW_NOTE' => 'Создать заметку или вложение' ,
'LNK_NEW_CALL' => 'Назначить звонок' ,
'LNK_NEW_EMAIL' => 'Отправить E-mail в архив' ,
'LNK_COMPOSE_EMAIL' => 'Создать E-mail' ,
'LNK_NEW_MEETING' => 'Назначить встречу' ,
'LNK_NEW_TASK' => 'Создать задачу' ,
'LNK_NEW_BUG' => 'Новая ошибка' ,
'LBL_ADD_BUSINESSCARD' => 'Ввести визитку' ,
'ERR_ONE_CHAR' => 'Пожалуйста, введите по меньшей мере одну букву или цифру для поиска ...' ,
'LBL_OPEN_TASKS' => 'Мои открытые задачи' ,
'LBL_SEARCH_RESULTS' => 'Результаты поиска' ,
'LBL_SEARCH_RESULTS_IN' => 'в',
'LNK_NEW_SEND_EMAIL' => 'Формирование E-mail' ,
'LBL_NO_ACCESS' => 'Доступ к разделу закрыт. Свяжитесь с администратором системы для получения соответствующих прав.',
'LBL_NO_RESULTS_IN_MODULE' => '-- Нет результатов --',
'LBL_NO_RESULTS' => '<h2>Ничего не найдено. Пожалуйста, повторите поиск.</h2><br>',
'LBL_NO_RESULTS_TIPS' => '<h3>Совет:</h3><ul><li>Убедитесь, что вы отметили необходимые модули.</li><li>Укажите более подробные условия поиска.</li><li>Если вы все еще ничего не нашли - попробуйте воспользоваться закладкой "Расширенный поиск" соответствующего модуля.</li></ul>',

'LBL_RELOAD_PAGE' => 'Пожалуйста, <a href="javascript: window.location.reload()">обновите страницу</a>, чтобы увидеть добавленный раздел.',
'LBL_ADD_DASHLETS' => 'Добавить разделы',
'LBL_ADD_PAGE' => 'Добавить страницу',
'LBL_DEL_PAGE' => 'Удалить страницу',
'LBL_WEBSITE_TITLE' => 'Веб-сайт',
'LBL_RSS_TITLE' => 'Ленты новостей',
'LBL_DELETE_PAGE' => 'Удалить страницу',
'LBL_CHANGE_LAYOUT' => 'Изменить макет',
'LBL_RENAME_PAGE' => 'Переименовать страницу',
'LBL_CLOSE_DASHLETS' => 'Закрыть',
'LBL_CLOSE_SITEMAP' => 'Закрыть',
'LBL_OPTIONS' => 'Параметры',

 // dashlet search fields
  'LBL_TODAY'=>'Сегодня',
  'LBL_YESTERDAY' => 'Вчера',
  'LBL_TOMORROW'=>' Завтра ',
  'LBL_LAST_WEEK'=>'Прошлая неделя',
  'LBL_NEXT_WEEK'=>'Следующая неделя',
  'LBL_LAST_7_DAYS'=>'Прошедшие 7 дней',
  'LBL_NEXT_7_DAYS'=>'Следующие 7 дней',
  'LBL_LAST_MONTH'=>'Прошлый месяц',
  'LBL_NEXT_MONTH'=>'Следующий месяц',
  'LBL_LAST_QUARTER'=>'Прошлый квартал',
  'LBL_THIS_QUARTER'=>'Этот квартал',
  'LBL_LAST_YEAR'=>'Прошлый год',
  'LBL_NEXT_YEAR'=>'Следующий год',
  'LBL_LAST_30_DAYS' => 'Прошедшие 30 дней',
  'LBL_NEXT_30_DAYS' => 'Следующие 30 дней',
  'LBL_THIS_MONTH' => 'Этот месяц',
  'LBL_THIS_YEAR' => 'Этот год',
  'LBL_MODULES' => 'Модули',
  'LBL_CHARTS' => 'Диаграммы',
  'LBL_TOOLS' => 'Разное',
  'LBL_WEB' => 'Веб',
  'LBL_SEARCH_RESULTS' => 'Результат поиска',


 // Dashlet Categories
   'dashlet_categories_dom' => array(
      'Module Views' => 'Модули',
      'Portal' => 'Портал',
      'Charts' => 'Графики',
      'Tools' => 'Сервис',
      'Miscellaneous' => 'Разное') ,

  'LBL_MAX_DASHLETS_REACHED' => 'Вы добавили максимальное количество разделов, установленное администратором. Пожалуйста, удалите один из существующих разделов для добавления нового.',
  'LBL_ADDING_DASHLET' => 'Добавление раздела ...',
  'LBL_ADDED_DASHLET' => 'Раздел добавлен',
  'LBL_REMOVE_DASHLET_CONFIRM' => 'Вы действительно хотите удалить этот раздел?',
  'LBL_REMOVING_DASHLET' => 'Удаление раздела ...',
  'LBL_REMOVED_DASHLET' => 'Раздел удален',
  'LBL_DASHLET_CONFIGURE_GENERAL' => 'Основные настройки',
  'LBL_DASHLET_CONFIGURE_FILTERS' => 'Фильтры',
  'LBL_DASHLET_CONFIGURE_MY_ITEMS_ONLY' => 'Мои записи:',
  'LBL_DASHLET_CONFIGURE_TITLE' => 'Заголовок:',
  'LBL_DASHLET_CONFIGURE_DISPLAY_ROWS' => 'Отображать строк:',

  'LBL_DASHLET_DELETE' => 'Удалить раздел',
  'LBL_DASHLET_REFRESH' => 'Обновить раздел',
  'LBL_DASHLET_EDIT' => 'Настроить раздел',

  'LBL_TRAINING_TITLE' => 'Обучение',

  'LBL_CREATING_NEW_PAGE' => 'Создание новой страницы...',
  'LBL_NEW_PAGE_FEEDBACK' => 'Вы создали новую страницу. Вы можете наполнить ее новым содержимым, воспользовавшись меню разделов.',
  'LBL_DELETE_PAGE_CONFIRM' => 'Вы действительно хотите удалить эту страницу?',
  'LBL_SAVING_PAGE_TITLE' => 'Сохранение заголовка страницы...',
  'LBL_RETRIEVING_PAGE' => 'Поиск страницы...',


// Default out-of-box names for tabs
  'LBL_HOME_PAGE_1_NAME' => 'Главная', ///
  'LBL_HOME_PAGE_2_NAME' => 'Sales', ///
  'LBL_HOME_PAGE_3_NAME' => 'Support', ///
  'LBL_HOME_PAGE_6_NAME' => 'Marketing', ///bug 16510, separate the support and marketing page from each other
  'LBL_HOME_PAGE_4_NAME' => 'Tracker', ///


  'LBL_CLOSE_SITEMAP' =>'Закрыть',

  'LBL_SEARCH' => 'Найти',
  'LBL_CLEAR' => 'Очистить',

  'LBL_BASIC_CHARTS' => 'Основные диаграммы',
  'LBL_REPORT_CHARTS' => 'Диаграммы отчётов',

  'LBL_MY_FAVORITE_REPORT_CHARTS' => 'My Favorite Reports',
  'LBL_GLOBAL_REPORT_CHARTS' => 'Global Team Reports',
  'LBL_MY_TEAM_REPORT_CHARTS' => 'My Team Reports',
  'LBL_MY_SAVED_REPORT_CHARTS' => 'My Saved Reports',

  'LBL_DASHLET_SEARCH' => 'Найти раздел',

  //ABOUT page
  'LBL_VERSION' => 'Версия',
  'LBL_BUILD' => 'Сборка',
  'LBL_VIEWLICENSE_COM' => '<P>Эта программа является свободным программным обеспечением; вы можете распространять его и/или изменять его в соответствии с условиями <a href="LICENSE.txt" target="_blank" class="body"> GNU Affero General Public License версии 3</a>, которая была опубликована Фондом свободного программого обеспечения, включая дополнительные разрешения, изложенные в заголовке исходного кода.</P>',
  'LBL_ADD_TERM_COM' => '<P>The interactive user interfaces in modified source and object code versions of this program must display Appropriate Legal Notices, as required under Section 5 of the GNU Affero General Public License version 3. In accordance with Section 7(b) of the GNU Affero General Public License version 3, these Appropriate Legal Notices must retain the display of the &quot;Powered by SugarCRM&quot; logo. If the display of the logo is not reasonably feasible for technical reasons, the Appropriate Legal Notices must display the words &quot;Powered by SugarCRM&quot;.</P>',
  'LBL_SUGAR_COMMUNITY_EDITION' => 'Sugar Community Edition',
  'LBL_SUGAR_PROFESSIONAL' => "Sugar Professional",
  'LBL_SUGAR_ENTERPRISE' => "Sugar Enterprise",
  'LBL_AND' => "and",
  'LBL_ARE' => "are",
  'LBL_TRADEMARKS' => 'trademarks',
  'LBL_OF' => 'of',
  'LBL_FOUNDERS' => 'Founders',
  'LBL_JOIN_SUGAR_COMMUNITY' => 'Присоединяйтесь к сообществу Sugar!',

  'LBL_DETAILS_SUGARFORGE' => 'Создавайте собственные дополнения к Sugar.',
  'LBL_DETAILS_SUGAREXCHANGE' => 'Покупайте и продавайте сертифицированные дополнения к Sugar.',
  'LBL_TRAINING' => 'Обучение',
  'LBL_DETAILS_TRAINING' => 'Узнайте больше об использовании Sugar в режиме онлайн и об интерактивных обучающих материалах.',
  'LBL_FORUMS' => 'Форумы',
  'LBL_DETAILS_FORUMS' => 'Обсуждайте систему с пользователями и разработчиками Sugar.',
  'LBL_WIKI' => 'Wiki',
  'LBL_DETAILS_WIKI' => 'Используйте базу знаний для поиска интересующей вас информации.',
  'LBL_DEVSITE' => 'Сайт разработчика',
  'LBL_DETAILS_DEVSITE' => 'Пользуйтесь публикуемыми материалами и полезными ссылками, чтобы быть в курсе последних разработок Sugar.',
  'LBL_GET_SUGARCRM_RSS' => 'Подписка на RSS:',
  'LBL_SUGARCRM_NEWS' => 'Новости SugarCRM',
  'LBL_SUGARCRM_TRAINING_NEWS' => 'SugarCRM Training News',
  'LBL_SUGARCRM_FORUMS' => 'Форумы SugarCRM',
  'LBL_SUGARFORGE_NEWS' => 'Новости SugarForge',
  'LBL_ALL_NEWS' => 'Все новости',
  'LBL_LINK_CURRENT_CONTRIBUTORS' => 'Click this link for a current list of Sugar contributors!',
  'LBL_SOURCE_CODE' => 'Source Code',
  'LBL_SOURCE_SUGAR' => 'Sugar - The world\'s most popular sales force automation application created by SugarCRM Inc.',
  'LBL_SOURCE_XTEMPLATE' => 'XTemplate - A template engine for PHP created by BarnabГЎs Debreceni',

  'LBL_SOURCE_NUSOAP' => 'NuSOAP - A set of PHP classes that allow developers to create and consume web services created by NuSphere Corporation and Dietrich Ayala',
  'LBL_SOURCE_JSCALENDAR' => 'JS Calendar - A calendar for entering dates created by Mihai Bazon',
  'LBL_SOURCE_PHPPDF' => 'PHP PDF - A library for creating PDF documents created by Wayne Munro',

  'LBL_SOURCE_PNGBEHAVIOR' => 'PNG Behavior - Adds support for PNG graphic format to Internet Explorer.',
  'LBL_SOURCE_JSONPHP' => 'JSON.php - A PHP script to convert to and from JSON data format by Michal Migurski.',
  'LBL_SOURCE_JSON' => 'JSON.js - A JSON parser and JSON stringifier in JavaScript.',
  'LBL_SOURCE_HTTP_WEBDAV_SERVER' => 'HTTP_WebDAV_Server - A WebDAV Server Implementation in PHP.',
  'LBL_SOURCE_JS_O_LAIT' => 'JavaScript O Lait - A library of reusable modules and components to enhance JavaScript by Jan-Klaas Kollhof.',
  'LBL_SOURCE_PCLZIP' => 'PclZip - library offers compression and extraction functions for Zip formatted archives by Vincent Blavet',
  'LBL_SOURCE_SMARTY' => 'Smarty - A template engine for PHP.',
  'LBL_SOURCE_OVERLIBMWS' => 'Overlibmws - JavaScript library for client-side windowing.',

  'LBL_SOURCE_YAHOO_UI_LIB' => 'Yahoo! User Interface Library - The UI Library Utilities facilitate the implementation of rich client-side features.',
  'LBL_SOURCE_PHPMAILER' => 'PHPMailer - A full featured email transfer class for PHP',
  'LBL_SOURCE_CRYPT_BLOWFISH' => 'Crypt_Blowfish - Allows for quick two-way blowfish encryption without requiring the MCrypt PHP extension.',

  'LBL_SOURCE_HTML_SAFE' => 'HTML_Safe - A parser that strips down all potentially dangerous content within HTML',
  'LBL_SOURCE_XML_HTMLSAX3' => 'XML_HTMLSax3 - A SAX parser for HTML and other badly formed XML documents',
  'LBL_SOURCE_YAHOO_UI_LIB_EXT' => 'Yahoo! UI Extensions Library - Extensions to the Yahoo! User Interface Library by Jack Slocum',
  'LBL_SOURCE_JSMIN' => 'JSMin - filter which removes comments and unnecessary whitespace from JavaScript files.',
  'LBL_SOURCE_SWFOBJECT' => 'SWFObject - Javascript Flash Player detection and embed script.',
  'LBL_SOURCE_TINYMCE' => 'TinyMCE - A WYSIWYG editor control for web browsers that enables the user to edit HTML contents',
  'LBL_SOURCE_EXT' => 'Ext - A client-side JavaScript framework for building web applications.',
  'LBL_SOURCE_RECAPTCHA' => 'reCAPTCHA - A free CAPTCHA service that helps to digitize books, newspapers and old time radio shows.', 
  'LBL_SOURCE_TCPDF' => 'TCPDF - A PHP class for generating PDF documents.',

  'LBL_DASHLET_TITLE' => 'Мои сайты',
  'LBL_DASHLET_OPT_TITLE' => 'Заголовок',
  'LBL_DASHLET_OPT_URL' => 'Адрес веб-сайта',
  'LBL_DASHLET_OPT_HEIGHT' => 'Высота раздела (в пикселях)',
  'LBL_DASHLET_SUGAR_NEWS' => 'Sugar-новости',
  'LBL_DASHLET_DISCOVER_SUGAR_PRO' => 'Discover Sugar',


);


?>